dmjio/miso

.travis.yml, default.nix
=> Added GHCJS cache, changed defaults

src/Miso/Html/Element.hs
=> Add center tag

ghcjs-src/Miso/Effect.hs
=> Add flipped Effect operator

README.md, release.nix
=> Added release.nix for hydra, added hydra badge

cabal.config
=> Changed default compiler to ghc, to satisfy stackage builds

README.md
=> Add logo, update README.md

default.nix
This is because I hate manually dragging and dropping zip files onto the s3 amazon console.
=> Make script to upload examples to s3

default.nix
=> Build with -Wall and -Werror

README.md
[ x ] - GHCJS Haddocks URL
[ x ] - todo-mvc
[ x ] - mario
[ x ] - simple
[ x ] - svg
=> Update URL for GHCJS haddocks & examples

ghcjs-src/Miso/Html/Internal.hs
=> Fix haddock bug for onWithOptions

.gitignore, README.md, default.nix, examples/websocket/Main.hs, examples/websocket/index.html, miso.cabal
=> Initial commit of websocket example code

examples/router/Main.hs, ghcjs-src/Miso/Router.hs, ghcjs-src/Miso/Subscription/History.hs
- Use `makeLenses` so as not to clash with the `lens` function from the `lens` package or `microlens`
- `HasURI` as an added convenience when calling `runRoute`
=> Added uri lenses, model argument to view handlers

.ghci, .ghcjsi, README.md
This PR aims to improve examples for local builds. Things I did so far:
- `mario` example now loads images correctly through `data-files`;
- README gained a "Building examples" section.
I also might improve documentation for examples here with extra comments and READMEs.
=> Improve on building examples locally

README.md, appveyor.yml
Put stack builds under CI in windows via Appveyor
=> Init Appveyor

README.md, examples/sse/LICENSE, examples/sse/client.nix, examples/sse/client/Main.hs, examples/sse/default.nix, examples/sse/nix/config.nix, examples/sse/nix/module.nix, examples/sse/server.nix, examples/sse/server/Main.hs, examples/sse/shared/Common.hs, examples/sse/sse.cabal
=> Cocreature sse example

ghcjs-src/Miso/Effect.hs
I remember being slightly confused about whether actions block so it
probably makes sense to point out in the docs that they don’t block.
=> Improve documentation of `Effect`

release.nix
=> Add haskell-miso and sse example to CI

ghcjs-src/Miso/Effect/DOM.hs, ghcjs-src/Miso/Effect/Storage.hs, ghcjs-src/Miso/Html/Internal.hs, src/Miso/Event/Types.hs
Here’s a first attempt at improving the haddocks. I’m by no means done making improvements but I’d rather merge reasonably small improvements than trying to finish it all at once.
=> Various haddock improvements

README.md
=> Add Flatris example

ghc-src/Miso/Html/Internal.hs, ghcjs-src/Miso/Html/Internal.hs
I’ve found those instances useful when writing middleware style code.
=> Derive Functor instances for View

src/Miso/Html/Element.hs
Comes in handy, especially when previewing with ghci.
=> Add link tag

README.md, default.nix, examples/file-reader/Main.hs, miso.cabal
cc @cocreature can I get a review
=> Initial commit of FileReader

jsbits/delegate.js
cc @FPtje, have tested this on your example with success, along with examples.
=> Propagate to parent event handlers when no event present

examples/mario/Main.hs
Previously each key press was creating a new loop of Time actions.
=> Fix action leak in mario example

README.md
The current one doesn't compile because Miso.String isn't imported.
=> README.md: Update Sample Application to reflect latest sample-app/Main.hs

default.nix
=> Initial snake commit

ghcjs-src/Miso/Subscription/WebSocket.hs
@FPtje can I get a review here.
Rebased your code with one additional commit to reconnect only when the socket has closed abnormally (when `CLOSED_NORMAL` is not the case). 
Note, this doesn't include client-side closing or reconnecting (just server). Handling client side socket closing / reopening goes back to managing dynamic subscriptions, which is something `miso` doesn't have at current.
=> Fixes websocket reconnection logic

examples/haskell-miso.org/client/Main.hs, examples/haskell-miso.org/server/Main.hs, examples/haskell-miso.org/shared/Common.hs
=> Fix responsive navigation menu in https://haskell-miso.org example

examples/haskell-miso.org/shared/Common.hs
Fix highlighting of the navigation menu page names when the URI is changed
=> Fix haskell-miso.org navigation menu

src/Miso/Router.hs
Previously miso made a distinction between fatal errors caused by
failures to parse parameters and non-fatal errors. In the case of
fatal errors miso did not try other routes. However, this does not
match the behavior of servant-server which will try other routes on
parse failures. Since the same routes are used on the server and the
client this can cause problems (and it is also simply confusing for
people coming from servant-server).
Here’s an example to demonstrate `servant-server`’s behavior:
```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeOperators #-}
import           Servant
import           Data.Text (Text)
import qualified Data.Text as Text
import           Data.Monoid
import           Network.Wai.Handler.Warp
import           Data.Proxy …
```
=> Remove FailFatal to match servant-server’s behavior

examples/haskell-miso.org/shared/Common.hs
cc @rihardsk, rebase with some additional changes.
=> Make topnav work with JS disabled. Closes #241

README.md, examples/canvas2d/Main.hs, examples/compose-update/Main.hs, examples/file-reader/Main.hs, examples/haskell-miso.org/client/Main.hs, examples/mario/Main.hs, examples/router/Main.hs, examples/sse/client/Main.hs, examples/svg/Main.hs, examples/three/Main.hs, examples/todo-mvc/Main.hs, examples/websocket/Main.hs, examples/xhr/Main.hs, exe/Main.hs, ghcjs-src/Miso.hs, ghcjs-src/Miso/Delegate.hs, ghcjs-src/Miso/Diff.hs, ghcjs-src/Miso/FFI.hs, ghcjs-src/Miso/Types.hs, jsbits/delegate.js, sample-app/Main.hs
addresses https://github.com/dmjio/miso/pull/318
=> addresses issue # 223

README.md
=> Added WebVR links

README.md
Tested in https://github.com/srid/slownews/commit/930d434bd3b2c66fc5ae11fc69e5180a2c50819d
=> Update Stack ghcjs

README.md, sample-app/default.nix
Fixes temporary build failure regression
=> Updated Miso's hashes

ghcjs-src/Miso.hs
@dmjio this produces slightly simpler (and hopefully slightly more efficient) core code. I got rid of the `atomicModifyIORef'` because AFAIK we have a single writer updating the model so there's never the risk of race conditions. I also think there's no risk of [reordering of memory operations](http://hackage.haskell.org/package/base-4.10.1.0/docs/Data-IORef.html#g:2) so I think a simple `writeIORef` suffices.
=> Update the model without atomicModifyIORef'

ghcjs-src/Miso/Diff.hs, jsbits/diff.js, tests/diff.test.js
Introduces 100% code coverage on `diff.js`, uses jest.
=> Initial commit of code-coverage, updates to diff logic

README.md, tests/.gitignore, tests/package.json, tests/run.sh
cc @RobertFischer @sectore 
To run the tests and build the coverage report:
```bash
cd miso/tests && ./run.sh
```
=> Initial commit of test-runner

sample-app/default.nix, sample-app/stack.yaml
=> Bump `sample-app` to miso `0.17.0.0`

ghcjs-src/Miso/Subscription/History.hs
=> Prepend slash correctly

README.md, ghcjs-src/Miso/FFI.hs, ghcjs-src/Miso/Html/Internal.hs, ghcjs-src/Miso/Subscription/Keyboard.hs, miso-ghcjs.nix, miso.cabal, tests/Main.hs
=> Sauce Labs integration

src/Miso/Util.hs
@dmjio added the smart constructor for Attributes.
Cheers!
=> Added smart constructor for Attributes

miso.cabal
=> Re-add tests flag, default to false

README.md, exe/Main.hs
=> Conform all three copies of the sample/simple app

miso-ghc.nix, miso-ghcjs.nix, miso.cabal
=> Bump to 0.21.0.0

ghcjs-src/Miso/Subscription/History.hs, src/Miso/Concurrent.hs
=> Initial commit of empty notify

src/Miso/Router.hs
cc @tysonzero, this PR squashes the merge commit and preserves attribution. Great work ! 🍺
=> Make router more flexible

src/Miso/Router.hs
=> Router fix

examples/haskell-miso.org/default.nix
=> Properly override ghcjs nix scripts

frontend-src/Miso.hs
=> Add stable name to short circuit eq

examples/haskell-miso.org/nix/aws.nix
Use nixops to put miso on AWS.
=> Put miso on AWS

src/Miso/Html/Element.hs
=> Fix typo in docs

README.md
PR for #475
* Update stack.yml indent
* Add desc for linux `xdg-open`
=> Update README.md for stack

jsbits/delegate.js, jsbits/diff.js, jsbits/isomorphic.js
Tabs and spaces were used interchangeably per line, and there was no setting on my editor
that dislayed it right. 
This PR only deals with the indentation. I've tried to avoid changing the formatting otherwise.
=> jsbits: Fixed indentation

frontend-src/Miso/Subscription/Keyboard.hs
This PR fixes the following issue:
- Open two tabs, the second of which runs a Miso application with a `keyboardSub`. Let it just print events
- Select the second tab (with the Miso application)
- Press `Ctrl + 1` to switch to the first tab (tested in chrome)
- Click the second tab again
You'll find that the `keyDown` events of `Ctrl` and `1` have fired
but the `keyUp` events have not
consequently, Miso holds both `Ctrl` and `1` in the `IOVar` state even though they're not depressed
For us that causes keybindings to stop working :slightly_smiling_face:
The approach is not new, it is the same as the one applied in a js library called [Keydrown](https://jeremyckahn.github.io/keydrown/)
=> keyboardSub: Assume keys are released on blur.

src/Miso/Html/Property.hs
=> Add data attribute

sample-app/default.nix
This should have been done in https://github.com/dmjio/miso/pull/485 but was omitted there.
=> Update sample-app according to the instructions in the README

default.nix, examples/haskell-miso.org/default.nix, examples/sse/default.nix, ghcjs-ffi/Miso/FFI.hs, jsbits/delegate.js, jsbits/diff.js, jsbits/isomorphic.js, jsbits/util.js, tests/Main.hs, tests/diff.test.js
https://developers.google.com/closure/compiler/docs/api-tutorial3#export
=> Export all functions to allow advanced optimizations.

ghc-src/Miso/String.hs
Hi, Not sure if this is very important but this PR should make Miso usable with GHC 7.10 (tested with this project https://gitlab.com/juliendehos/miso-test).
=> remove TypeApplications for building with GHC 7.10

default.nix, examples/haskell-miso.org/default.nix, examples/haskell-miso.org/nix/config.nix
Use `GHCJS 8.6` on https://haskell-miso.org, use `ADVANCED OPTIMIZATIONS`
=> Enable closure-compiler advanced optimizations on haskell-miso.org

.travis.yml
=> Initial commit of Travis CI build.

README.md
Add Travis CI status badge to `README.md`
=> Add build status to miso from travis

.travis.yml, tests/package.json
=> Run miso tests w/ yarn in travis.

LICENSE, miso.cabal
=> Bump to 2020

jsbits/delegate.js, jsbits/diff.js, jsbits/isomorphic.js, jsbits/util.js
=> Initialize window if empty

jsbits/diff.js, tests/diff.test.js
=> Support base case for prepending keys.

README.md
cc @basvandijk @tysonzero @FPtje @parthshah31
=> Add commercial users section

README.md, examples/file-reader/Main.hs, ghcjs-ffi/Miso/FFI.hs, jsaddle-ffi/Miso/FFI.hs, tests/Main.hs
Add consoleLogJSVal for backwards compat.
=> consoleLog should operate on MisoString

jsbits/diff.js
=> Adjust keys patch to work correctly when sorting large keyed lists.

jsbits/diff.js
Deletion from the end of list will keep copying from occurring.
=> Remove accidentally quadractic behavior

README.md
=> Add commercial user

frontend-src/Miso/Subscription/WebSocket.hs, ghcjs-ffi/Miso/FFI/WebSocket.hs, jsaddle-ffi/Miso/FFI/WebSocket.hs
=> Add close to websocket API.

default.nix
=> Nix tweaks

docker/Dockerfile, docker/README.md, docker/docker-compose.yml, sample-app/.gitignore
Following [this issue](https://github.com/dmjio/miso/issues/568) I added the dockerization of miso to the official repo.
It would be nice, if someone could test this on Linux and MacOS.
=> Add docker support

frontend-src/Miso/String.hs, src/Miso/Event/Decoder.hs, src/Miso/Event/Types.hs, src/Miso/Html/Event.hs
- Adds `KeyInfo`, `keyInfoDecoder`, `onKeyDownWithInfo`
=> KeyInfo Decoder

examples/miso-examples.cabal, miso.cabal
=> Bump to 1.5.1.0

default.nix
Add jsaddle-wkwebview to ghc865 packages.
=> jsaddle-wkwebview

ghc-src/Miso/Html/Internal.hs
=> Make no element tags when appropriate.

src/Miso/Html/Element.hs
I didn't consider how haddock would render this when I first
committed and it's really ugly. This fixes that.
=> Improve haddock for style_ and script_

ghc-src/Miso/Html/Internal.hs, ghcjs-ffi/Miso/FFI.hs, jsaddle-ffi/Miso/FFI.hs, jsbits/isomorphic.js
- Remove unnecessary 'import Data.Monoid'
- Update iso logic for example
=> Concatenate multiple classes together

sample-app-jsaddle/README.md
=> Update README.md to add external javascript files

README.md
This adds my game to the list of examples. Feel free to disregard if irrelevant.
=> README.md: add Pixel Card Wars to examples' list

jsbits/diff.js
=> Diffing algorithm - allow props with zero value

src/Miso/Html/Property.hs
As proposed in #611
Just saw that this issue was still open and I wanted to close it. I hope that's all there is to this.
=> Add inline styling to props

src/Miso/Html/Property.hs
According to https://www.w3schools.com/tags/att_img_loading.asp
it can be used to make the images lazily load.
=> Add loading_ property

default.nix, examples/haskell-miso.org/default.nix, examples/sse/default.nix, nix/haskell/packages/ghc8107/default.nix, nix/haskell/packages/ghcjs/default.nix, nix/haskell/packages/source.nix, nix/nixpkgs.json, nix/overlay.nix, sample-app-jsaddle/default.nix, sample-app-jsaddle/shell.nix
- Use the newly reinstated GHCJS per @falsifian 's work in https://github.com/NixOS/nixpkgs/issues/133271#issue-964150987
- Bump GHC to 8.10.7
=> Move to ghcjs8107.

jsbits/delegate.js, jsbits/diff.js, jsbits/isomorphic.js, tests/diff.test.js
Some js files're using 2 and 4 space as indent mixed.
=> Fix indent in js files

README.md
=> Update README.md, fix "miso slack" button

.github/workflows/main.yml
=> Bump cachix versions

README.md
The links to SSE and Pixel Card Wars also seem to be dead but I'm not sure if that's temporary so I left them be
=> Fix simple example source link

README.md
The old GitHub account was renamed.
=> docs (README): Update links to Gabriella439

examples/haskell-miso.org/nix/aws.nix, examples/miso-examples.cabal, miso.cabal
Version bump for https://github.com/dmjio/miso/commit/2797f7529fb0482749219d3544491a096a0c463c
=> Bump to 1.8.4.0

README.md
Commit f7848e9028a477200a6ac8bff2951d63dc4c60e8 moved the location of `nixpkgs.json`. This PR adjusts sources to changes.
=> Update nixpkgs reference

examples/haskell-miso.org/server/Main.hs
=> Add robots.txt to haskell-miso.org

examples/canvas2d/Main.hs, examples/file-reader/Main.hs, examples/three/Main.hs
When differentiating between GHC JS and GHCJS. #759
=> Use javascript_HOST_ARCH over ghcjs_HOST_OS

README.md
- Prioritize matrix over IRC and slack.
=> Move to matrix.org

haskell-miso.org/server/Main.hs, haskell-miso.org/shared/Common.hs
- Slack -> Matrix.org
- FFI inclusive of WASM
=> Haskell miso updates

.github/workflows/main.yml, default.nix, nix/overlay.nix, sample-app-jsaddle/default.nix, sample-app-jsaddle/shell.nix, sample-app/default.nix
- Build tagged releases in CI to catch nix errors
=> Add tagged releases to CI

miso.cabal, src/Miso/Runner.hs
First two commits clean things up a bit in passing.
=>  Use environment variable for runner port 

.github/workflows/main.yml, default.nix, haskell-miso.org/nix/aws.nix, haskell-miso.org/nix/machine.nix, haskell-miso.org/nix/module.nix, haskell-miso.org/nix/nginx.nix, nix/overlay.nix
- Add NixOS test runner
- Test the service can be curl'd.
- Separate out nixops specific (deployment objects) from other modules
- Add nginx.nix, server.nix -> machine.nix
- Don't rely on packageOverrides in this hash of nixpkgs
=> Refactor NixOS modules, and NixOS test runner.

examples/components/Main.hs, haskell-miso.org/client/Main.hs, haskell-miso.org/haskell-miso.cabal, haskell-miso.org/server/Main.hs, haskell-miso.org/shared/Common.hs, jsbits/diff.js, jsbits/isomorphic.js, jsbits/util.js, nix/wasm/default.nix, src/Miso.hs, src/Miso/FFI.hs, src/Miso/Internal.hs, src/Miso/Types.hs
Adds the analog of the `miso` function, but it operates on a top-level `Component` cc @amesgen
=> Add misoComponent function

cabal.project, default.nix, examples/sse/client/Main.hs, examples/sse/default.nix, examples/sse/nix/machine.nix, examples/sse/nix/module.nix, examples/sse/server/Main.hs, examples/sse/shared/Common.hs, examples/sse/shell.nix, haskell-miso.org/nix/aws.nix, nix/overlay.nix, shell.nix
- Bring back SSE example
- Test the server opens listen socket w/ QEMU test
- Add shell.nix to sse, default to ghc
=> Componentize SSE example

nix/wasm/default.nix, src/Miso.hs, src/Miso/Runner.hs
Remove redundancies, fix issue with CPP
=> Adjust CPP for wasm ci build.

.github/workflows/main.yml
=> Use nix-channel --update in CI

.github/workflows/main.yml, src/Miso/FFI.hs, src/Miso/Internal.hs
- Remove some unnecessary CPP as well
=> Remove redundant imports and name shadowing in .Internal

examples/components/Main.hs, examples/miso-examples.cabal, examples/shell.nix, jsbits/isomorphic.js, src/Miso.hs, src/Miso/Internal.hs
=> Add virtual DOM integrity check to DebugPrerender

jsbits/diff.js
Ensure that components are accounted for in the worst case diffing scenario for the `syncChildren` optimization path
=> Mount component during syncChildren worst case.

haskell-miso.org/shared/Common.hs, miso.cabal
=> Use language and links more inclusive of the WASM backend 

src/Miso.hs
`startComponent` should mount on the `<body>` element.
=> Mount startComponent to body

examples/canvas2d/Main.hs, examples/components/Main.hs, examples/compose-update/Main.hs, examples/file-reader/Main.hs, examples/mario/Main.hs, examples/mathml/Main.hs, examples/router/Main.hs, examples/simple/Main.hs, examples/sse/client/Main.hs, examples/sse/server/Main.hs, examples/sse/shared/Common.hs, examples/svg/Main.hs, examples/three/Main.hs, examples/todo-mvc/Main.hs, examples/websocket/Main.hs, examples/xhr/Main.hs, haskell-miso.org/client/Main.hs, haskell-miso.org/server/Main.hs, haskell-miso.org/shared/Common.hs
=> Format example code w/ fourmolu

examples/simple/Main.hs, examples/svg/Main.hs, src/Miso/Event/Decoder.hs, src/Miso/Event/Types.hs, src/Miso/Html/Event.hs, src/Miso/Subscription/Mouse.hs, src/Miso/Subscription/Window.hs
- Introduces 'move', 'out', 'cancel', 'enter', 'down', etc. for pointer
- Defines PointerEvent type, pointerDecoder
- Move svg an simple examples to PointerEvent
=> Initial commit of PointerEvent

src/Miso/Router.hs
- Location 'loc' is shadowing 'l'
=> Fix router name shadowing bug.

examples/components/Main.hs, jsbits/diff.js, src/Miso/Html/Event.hs, src/Miso/Internal.hs, src/Miso/Render.hs, src/Miso/Types.hs
- Makes `onUnmounted`, `onMounted` synonyms of `onBeforeDestroyed` and `onCreated`
=> Remove `ComponentOptions`, use `[Attribute action]`

.github/workflows/main.yml, examples/sse/client/Main.hs, examples/sse/server/Main.hs, examples/sse/shared/Common.hs
- Put SSE under CI
- Update sse to use new API
=> Updates to sse

src/Miso/Effect.hs
- Update variable namings
- Simplify / refactor code for readability
=> Refactor Effect / Transition code for readability

examples/simple/Main.hs, jsbits/miso.js, src/Miso/FFI.hs
=> Exorcise window from the codebase

tests/miso.spec.js
- Tests that events can be routed through the virtual DOM
- Test mounting / unmounting of event delegation.
- Check `eventJSON` parsing.
=> Add test of event delegation.

examples/miso-examples.cabal, haskell-miso.org/nix/nginx.nix, miso.cabal
=> Prepare major release, v1.9.0.0

default.nix, haskell-miso.org/client/DevelMain.hs, haskell-miso.org/client/Main.hs, haskell-miso.org/client/shell.nix, haskell-miso.org/default.nix, haskell-miso.org/haskell-miso.cabal, haskell-miso.org/server/Main.hs, haskell-miso.org/shared/Common.hs, nix/overlay.nix, src/Miso.hs, src/Miso/FFI.hs
- Use 'rapid' w/ jsaddle-warp and `C-c m` `DevelMain` emacs integration
- Create haskell-miso-dev derivation
- Add dev flag to cabal file for haskell-miso.org/client
- FFI for location.reload()
=> Add hot reload functionality via the 'rapid' package

eslint.config.js, js/miso.js, js/miso.spec.js, package.json, yarn.lock
- Assume browser environmnet in `miso.spec.js`
- Add `beforeEach (() => document.body.innerHTML = '';)` call
- Drop explicit `jsdom.JSDOM()` references
- Prettify new source
- Update `yarn.lock`
=> Adds jest-environment-jsdom

js/miso.js, js/miso.spec.js, src/Miso.hs, src/Miso/FFI.hs, src/Miso/Internal.hs
- Use industry nomenclature
- Link to wikipedia article on hydration
- Rename all occurrences
=> copyDOMIntoVTree -> hydrate

package.json, ts/miso.spec.ts, ts/miso.ts, ts/miso/dom.ts, ts/miso/event.ts, ts/miso/iso.ts, ts/miso/types.ts
- Add `types.ts` module
- Remove `any`
- `miso.spec.js` -> `miso.spec.ts`
- Remove named field accessors `obj['domRef'] -> obj.domRef`
- [-] ~Port `miso.spec.ts` to use `miso/types.ts`~
- [-] ~Use a tagged union for `domRef`~
=> Typescriptify

src/Miso/Effect.hs
Only explicitly import MonadFail if we're dealing with ghc86.
=> Remove MonadFail warnings on ghc9122

src/Miso.hs, src/Miso/Subscription/History.hs
Combines `getURI` / `getCurrentURI`
=> Consolidate getURI / getCurrentURI

src/Miso/Internal.hs
Now that `Effect` and `Transition` have been unified, drop `mail`, prefer `notify`.
=> Drop unused mail function.

README.md
Now the code started a server on port 8008 as the comment suggests.
=> Update bash script to start the sample-app

README.md, haskell-miso.org/shared/Common.hs
- Adds Discord server badge from shields.io
- Updates https://haskell-miso.org to include Discord link
=> Add our discord server to the README.md and website

.github/workflows/main.yml, README.md, default.nix, docker/Dockerfile
- Populate and replace `miso-haskell` cache w/ `haskell-miso-cachix` cache
- Upgrades GitHub actions
- Updates docs
=> Upgrade cachix cache to use new auth scheme.

haskell-miso.org/nix/nginx.nix
`"${coverage}/report"` -> `coverage`
=> Coverage derivation using incorrect path.

examples/canvas2d/Main.hs
=> Drop translate from canvas2d example.

.github/workflows/main.yml, nix/wasm/default.nix
- Uncomments previously commented out build due to `cabal update` hanging
- OOD solved by adding a an extra GC during CI
=> Reinstate WASM build in CI

src/Miso/Event/Types.hs
- Link to and document Capture
=> Avoid boolean blindess, document Capture.

README.md
- Update ghcjs instructions to use nixpkgs staging branch
=> Update ghcjs install instructions to use nixpkgs staging

package.json
- Use find's `delete`
- Piggyback on `tsc clean`
=> Update bun run clean in package.json

src/Miso/Lens.hs
What this does: use single block of code for each example instead of multiple separate ">" blocks
Also made few examples simpler/more uniform and added haddock links where appropriate.
Before (left) vs. After
=> Improve Lens haddocks

src/Miso.hs
Add soup emoji operator as an alias for miso.
=> Add soup emoji function alias.

README.md
Updates README.md to include `cabal update`
=> Add wasm32-cabal-update instructions

README.md, cabal.project
Look like you forgot to update the README following a force push 5 months ago.
=> Point to last splitmix commit

.github/workflows/main.yml, default.nix, haskell-miso.org/nix/nginx.nix, nix/legacy/haskell/packages/ghcjs/default.nix, nix/overlay.nix
Uses `cabal haddock-project` to build haddocks (w/ deps. haddocked as well)
=> cabal haddock-project

src/Miso/Internal.hs
Use `Int` accumulator instead of an infinite lazy list
=> Use IORef Int instead of IORef [Int] for global vars

src/Miso.hs, src/Miso/Effect.hs
Use more idiomatic `with` prefix when dealing when continuations
=> sink -> withSink

src/Miso/Types.hs
=> Add MountPoint, use Events synonyms

examples/components/Main.hs, examples/sse/server/Main.hs, haskell-miso.org/server/Main.hs, src/Miso/Internal.hs, src/Miso/Lens.hs, src/Miso/Types.hs
=> Tuple lenses, _1, _2

README.md
Dear @juliendehos,
Thanks for the `miso-invaders` example. I'd like to add it to the README.md.
P.S. is there any way we can change the audio track :)
=> Add Space Invaders demo

src/Miso/Canvas.hs
This PR introduces a callback to the `canvas` function that can be used to abstract over 2d and 3d canvas draws.
This is the first step towards a declarative API for WebGL / three.js.
=> Abstract over canvas dimension, interpretation.

examples/components/Main.hs, src/Miso.hs, src/Miso/Effect.hs, src/Miso/Internal.hs
=> Generalize SubName to Ord key => key.

bun.lock, package.json
=> bun update

src/Miso/Event/Types.hs
=> Add audioVideoEvents Map

miso.cabal, nix/haskell/packages/ghc/default.nix, nix/haskell/packages/ghcjs/default.nix, src/Miso/Lens/TH.hs
Adds simple Lens reification for product newtype and data types.
=> Add Miso.Lens.TH.makeLenses

src/Miso/Util.hs, src/Miso/Util/Lexer.hs, src/Miso/Util/Parser.hs
=> Add common lexer, parser combinators to Miso.Util

README.md, cabal.project, examples/fetch/Main.hs, examples/miso-examples.cabal, src/Miso/Fetch.hs
=> Drop splitmix fork for WASM, use fetchJSON

src/Miso/Property.hs
=> Add objectProp, used for native.

README.md, examples/fetch/Main.hs, src/Miso/FFI/Internal.hs, src/Miso/Fetch.hs
=> Make `fetch` an `Effect`

src/Miso/Style/Color.hs
=> Add `hsla`

src/Miso/Style.hs
=> Haddockery (MDN links) for `Miso.Style`

README.md, haskell-miso.org/server/Main.hs, haskell-miso.org/shared/Common.hs, miso.cabal, package.json
Emphasizes mobile / native in `README.md`, cabal file, and website.
=> Add `miso-native` to README.md 📱 

haskell-miso.org/shared/Common.hs
=> Add `miso-lynx` section to website 🍜 🐈

src/Miso/Html/Property.hs
=> Add `classes_` combinator.

src/Miso/Lens.hs
Now that `Effect` is `RWS`, we can add `view`.
=> Add `Miso.Lens.view`

miso.cabal, src/Miso.hs, src/Miso/Runtime.hs
=> `.Internal` -> `.Runtime`

src/Miso/Runtime.hs
Move `subscriber` to use errorful / successful callbacks
=> Update subscribe to use errorful callback

src/Miso/Event/Decoder.hs, src/Miso/Event/Types.hs
=> Add fields to `PointerEvent` and its `Decoder`.

src/Miso/Lens.hs, src/Miso/Lens/TH.hs, src/Miso/Util.hs
=> Adds `makeClassy`

src/Miso/Lens.hs
For `optics`, `lens`, `microlens` users.
=> Add Van Laarhoven conversion functions.

src/Miso/Lens.hs
Add synonyms for `Lens` fields
=> Add `Getter`, `Setter` types

src/Miso/Runtime.hs, src/Miso/Types.hs
More combinators can be added (like for `optics`), since `Binding` is generic over any lens
=> Add additional bidirectional reactive combinators `<-->`, `<--->`.

src/Miso/FFI.hs, src/Miso/FFI/Internal.hs, src/Miso/Media.hs
=> 📋 Add `Clipboard` support.

miso.cabal, src/Miso/String/QQ.hs
=> Add `Miso.String.QQ`

src/Miso/Types.hs
This is to avoid situations where list concatenation in the `View` becomes awkward in the presence of conditional logic. For example,
```haskell
view m =
div_
([ id_ "some-id"
] ++
[ className "foo" | m ^. hasFoo
])
[ "test" ]
```
This is a common pattern, and it can now be simplified to the below
```haskell
view m =
optionalAttrs
div_
[ id_ "some-id"
]
(m ^. hasFoo)
[ className "foo"]
[ "test" ]
```
The above example solves this problem for `Attribute`, but the same exists with child lists, as seen below.
```haskell
view m =
div_
[ id_ "some-id"
]
[ "test" ]
(m ^. hasFoo)
[ "foo" ]
```
In the above, the conditional `m ^. hasFoo` will * append * the child list `[ "foo" ]` to `[ "test" ]` resulting in `[ "test", "foo" ]`.
=> Add helper functions `optionalAttrs`, `optionalChildren`.

src/Miso/Subscription/SSE.hs
Adds deterministic resource handling to `sseSub` on `EventSource`
=> `close` out `EventSource`

src/Miso/Runtime.hs
When binding models, use transactional memory.
=> Use `stm` for model synchronization.

miso.cabal, src/Miso.hs, src/Miso/Binding.hs, src/Miso/Types.hs
=> Add `Miso.Binding`

src/Miso/Html/Event.hs
=> Add additional `with*` variants for click events

src/Miso/Event/Types.hs, src/Miso/Html/Event.hs
Adds touch events map and event handlers
=> Add touch event `Map` and handlers

src/Miso/String.hs
=> Add `To`/`FromJSONKey`

src/Miso/FFI.hs, src/Miso/FFI/Internal.hs
=> Add `FileReader`

src/Miso/FFI.hs, src/Miso/FFI/Internal.hs
=> Add `FormData`

src/Miso/Effect.hs
adds modifyJSM, beforeAll, and afterAll
=> adds utility functions for JSM in Effect

src/Miso.hs, src/Miso/Router.hs, src/Miso/Runtime.hs, src/Miso/Types.hs
This initialModel action is run before a component is rendered to give every component a chance to initialize its own state.
=> Adds `initialModel :: Maybe (JSM model)` to `Component`
