jsbits/diff.js

When diffing between a text node and an element, the correct swapping function should be executed. 
To reproduce the bug:
```haskell
{-# LANGUAGE RecordWildCards #-}
module Main where
import Miso
import Miso.String
type Model = Bool
main :: IO ()
main = startApp App {..}
where
model  = False
update = updateModel
view   = viewModel
events = defaultEvents
subs   = []
updateModel :: Action -> Model -> Effect Model Action
updateModel Action m = noEff ( not m )
data Action = Action
deriving (Show, Eq)
viewModel :: Bool -> View Action
viewModel x = div_ [] $ button_ [ onClick Action ] [] : handle x
where
handle True = [ text $ pack "fooo" ]
handle False = [
ul_ [] [
li_ [] [ text $ pack "hey" ]
, li_ [] [ text $ pack "there" ]
]
]
```
This fix diffs text and element nodes properly.

Swap text and element diffing cases

---

ghcjs-src/Miso/Effect/XHR.hs

cc @bitemyapp @alpmestan, this should provide backwards compat for latest servant combinators. Will rebase and add more cpp if I forget any new ones.
`CaptureAll` was added in `8.0.1`

Apply CPP to new combinators for backwards compat

---

default.nix
release.nix

Might as well build `miso` with GHCJS HEAD, alongside release.

Build GHCJS HEAD version alongside release

---

examples/mario/Main.hs
ghcjs-src/Miso/Subscription/Keyboard.hs
miso-ghc.nix
miso-ghcjs.nix
miso.cabal
src/Miso/Concurrent.hs

In `Miso.Concurrent`, `EventWriter` uses an unbounded channel to receive events. This causes linear growth of memory under high load. The mario example demonstrates this very well.
This PR introduces `BoundedChan` to drop unnecessary events and specify an upper bound on the number of messages that can exist in memory at any given time.
This PR also adds strictness to the mario model example, and replaces the `SkipChan` implementation from `Control.Concurrent` with a single synchronizing variable.

Added BoundedChan, simplified Notify, replace SkipChan imp.

---

default.nix

Since `phantomjs2` is broken on darwin, temporarily disable. This will allow users to build `miso` on nix under Darwin. 
https://github.com/NixOS/nixpkgs/issues/22172

Temporarily disable tests on Darwin

---

ghc-src/Miso.hs
miso.cabal

`Miso` was missing from the export list for `ghc` src

Expose Miso from ghc-src

---

ghc-src/Miso/Html/Internal.hs
ghcjs-src/Miso/Html/Internal.hs
ghcjs-src/Miso/Router.hs
miso-ghc.nix
miso.cabal

To allow type-safe links to be generated on the server, w/o causing orphans

Share MkLink across ghc/ghcjs-src

---

README.md
examples/mario/Main.hs
examples/router/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
exe/Main.hs
ghcjs-src/Miso.hs
ghcjs-src/Miso/Types.hs

Per @NickSeagull, it would be very useful to have an initial action that is executed on application load. This is relevant for:
- Retrieving entire models under an isomorphic context
- Executing arbitrary actions on application start (i.e. initializing a canvas) 
The user can specify `NoOp` (identity), in cases where no actions are required.

Added initial action

---

examples/sse/LICENSE
examples/sse/client.nix
examples/sse/client/Main.hs
examples/sse/default.nix
examples/sse/nix/config.nix
examples/sse/nix/module.nix
examples/sse/server.nix
examples/sse/server/Main.hs
examples/sse/shared/Common.hs
examples/sse/sse.cabal

I’m opening this not because it’s finished (although it does work) but so that we have something to look at while we flesh out the details.
1. The examples is deliberately simple and dumb. Personally I like that way since it makes it very clear what this example is focusing on but I can try coming up with something a bit more complex if you prefer that.
2. Currently the backend is just a separate application. Should I try to integrate it in the `haskell-miso.org` backend? The URl and the port also need to be updated before this is merged (I just needed something to test it :))

Add sse example, fixes #196

---

.gitignore
README.md
examples/compose-update/Main.hs
examples/haskell-miso.org/client/Main.hs
examples/mario/Main.hs
examples/router/Main.hs
examples/sse/client/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
examples/xhr/Main.hs
exe/Main.hs
ghcjs-src/Miso.hs
ghcjs-src/Miso/Effect.hs
ghcjs-src/Miso/Router.hs
ghcjs-src/Miso/Types.hs
miso.cabal
src/Miso/Lens.hs

This is an implementation of the ideas that I was trying to explain to you yesterday. I tried splitting the individual changes up into small self-contained commits so hopefully it’s easy to digest but I’ll give a quick summary anyway:
* `Effect` has been generalized to allow an arbitrary number of actions instead of just `0` and `1`. This is a breaking change but the smart constructors are unaffected so I think the actual breakage is not likely to be so bad.
* I moved the `Lens` utils to a separate module. This is not necessary but it feels cleaner. I’m completely fine with reverting this if you prefer that.
* This is the main part: I added `composeUpdate` which is the analogue of standard function composition but also takes care of combining the effects and I added `zoomUpdate` which …

Support composable update functions

---

README.md
examples/compose-update/Main.hs
examples/haskell-miso.org/shared/Common.hs
examples/router/Main.hs
examples/sse/shared/Common.hs
exe/Main.hs
ghc-src/Miso/Html/Internal.hs
ghc-src/Miso/String.hs
ghcjs-src/Miso/Html/Internal.hs
ghcjs-src/Miso/String.hs

Will get around having to `pack` everything.
- Re-exported `Data.Monoid` from `Miso.String`
- Removed silly `ToMisoString Value` instance.
- Added `ms` function as a concise `toMisoString`
cc @cocreature, can I get a review here.

Remove ToMisoString constraint on text

---

ghc-src/Miso/Html/Internal.hs
ghcjs-src/Miso/Html/Internal.hs

I'm not sure if there was a reason this instance wasn't defined, but it's pretty trivial to write and at least for me seems to improve the ergonomics.

add IsString instance for views

---

src/Miso/Html/Element.hs

Useful for embedding external scripts

Add script tag

---

ghcjs-src/Miso.hs
src/Miso/Concurrent.hs

This PR performs twofold:
- Ensures we notify the redrawer only when we are certain an action exists. Fixing #255  
- Evaluates effects asynchronously. Previously, evaluating accumulated `effects` was blocking redrawing.
cc @cocreature @FPtje

Async effects

---

examples/haskell-miso.org/server/Main.hs
examples/haskell-miso.org/shared/Common.hs
examples/router/Main.hs
examples/sse/server/Main.hs
examples/sse/shared/Common.hs

These fixes are necessary for servant >= 0.10 and >= 0.11. The
alternative to the CPP would be to just drop support for servant <
0.11 but since until recently servant-0.9 was still the version in
stackage LTS (all snapshots < LTS 9.0), I think it makes sense to
support it a bit longer. nixpkgs unstable has also moved to servant-0.11.

Fix build with servant >= 0.10

---

README.md

Update Miso version used in Stack quick start, and swap tabs for spaces to ensure copy/paste from quick start works smoothly.

---

ghcjs-src/Miso/Subscription/History.hs

I needed the URL fragment in the app I'm building. Found out they were missing 🍜
This PR fills in `uriScheme` and `uriFragment`
They were set to empty strings, but they can easily be retrieved from `window.location`, like `uriQuery` and `uriPath` are.
Two notes:
- I didn't touch `uriAuthority`, because I'm not sure how to construct it.
- The value filled in for `uriPath` strips the first `/` character, which seems to oppose the Haddock of [URI](http://hoogle.lumi.guide.local/file/nix/store/qw0lvqkyl0gicmhdwmfc26ari8dyqdg3-network-uri-2.6.1.0/share/doc/x86_64-linux-ghc-8.0.2/network-uri-2.6.1.0/html/Network-URI.html#t:URI). I didn't touch this because I have a gut feeling that there's a really good reason for this.

Added more info to URI returned by getCurrentURI

---

ghcjs-src/Miso.hs

Tuples are lazy so without this change the model will never actually
be forced in the foldl' (foldEffects …) which could lead to spaceleaks.

Add BangPatterns to foldEffects

---

ghcjs-src/Miso/FFI.hs
miso-ghcjs.nix
miso.cabal
tests/Main.hs

Fix `jsvalToValue` function. Allow for correct parsing of json between Haskell and JavaScript.

jsvalToValue

---

ghcjs-src/Miso/Types.hs
miso.cabal

This monad is useful for succinctly expressing model transitions. We use it a lot at LumiGuide. It's especially useful when used in combination with the stateful [lens operators](http://hackage.haskell.org/package/lens-4.15.4/docs/Control-Lens-Operators.html) (all operators ending in "`=`").
@FPtje I removed our `TransitionM` type synonym because I think it adds to much noise.

Introduce the Transition monad

---

ghcjs-src/Miso/Subscription/History.hs

`pushStateNoModel` and `replaceTo'` respectively each call `notify chan` as their last step, so there's no need to call `notify chan` a second time when they are called in `pushURI` and `replaceURI`.

remove redundant calls to notify

---

ghc-src/Miso.hs

This is a follow up to #301. Since it’s reexported on `ghcjs` it makes sense to reexport it on `ghc` as well.

Reexport Miso.Router from the top-level Miso module

---

jsbits/diff.js

The xlink:class prevents css styling from working.
```css
/* default.css */
.myClass { stroke: red; }
```
```haskell
-- some code that generates svg elements
line_ [class_' "myClass", x1_ "0", y1_ "0", x2_ "2", y2_ "3"]
```
```html
<head>
<link rel="stylesheet" href="default.css"/>
</head>
<body>
<script language="javascript" src="js/all.js" defer></script>
</body>
```
Miso will insert the svg element `<line xlink:class="myClass" ...>`. The result is that the styling in `default.css` will not apply to that element. If we use the `class` attribute directly everything works fine.
I see how the xlink stuff could be important in relation with the `href` attribute. But why for `class`?

Do not generate 'xlink:class' attributes for svg elements

---

ghc-src/Miso/String.hs
ghcjs-src/Miso/String.hs

This can be useful when an event provides a `MisoString` but you want
to pass that `MisoString` to an API that expects `Text`.

Add fromMisoString to `ToMisoString` typeclass

---

examples/svg/Main.hs
examples/svg/Touch.hs
ghcjs-src/Miso/Html/Internal.hs
jsbits/delegate.js
miso.cabal
src/Miso/Event/Decoder.hs

As this is a proof of concept, the implementation is quite limited (at the time of initial commit, only the SVG example works, others are most likely broken). As the Haskell code hasn't changed much, parts of the functionality are being simulated by the `objectsToJSON` function.
The general plan is to change the type of `decodeAt` to `[[MisoString]]`. This will allow for the specification of multiple targets from which to retrieve information. This gets passed to `objectsToJSON`, which returns an array of objects in the same order specified within `decodeAt` by making multiple calls to `objectToJSON`.
As a slightly related, can anyone see if they are still getting the error which @FPtje reported in ghcjs/ghcjs-base#88. At the moment, I'm dealing with this using a temporary fix I got from …

List of Objects and Multi-target Decoding

---

stack/ghcjs801/stack.yaml

Two things:
1. Need a note about `~/.stack/config.yaml` having `match-exact` in place, or it tries to use GHC 8.0.2 libraries and explodes while building GHCJS. That note will hopefully save people lots of time.
2. Need the miso version number, or Stack thinks the dependency is the folder `./miso` instead of the `miso` library.

ghcjs801 stack.yaml update

---

README.md
examples/compose-update/Main.hs
examples/mario/Main.hs
examples/svg/Main.hs
examples/todo-mvc/Main.hs
ghcjs-src/Miso/String.hs
sample-app/Main.hs

Creates instances of `ToMisoString` for `Float`, `Double` and `Int`.  Also updates the examples to reflect the change.
Some notes:
- `sample-app/default.nix` will need to pin Miso to a commit on or after the one that merges this PR, otherwise it won't compile
- Same for the `README.md` (line 268)
- The `fromMisoString` function assumes the type of the js object and that it can be parsed as a number. It means the function is unsafe. Not *too* bad if the end user knows what they're doing.

ToMisoString instances for Float, Double and Int

---

examples/file-reader/Main.hs
jsbits/delegate.js
src/Miso/Html/Event.hs

Take the following program:
```haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where
import Miso ( App(..), Transition )
import qualified Miso
import Miso.Html
import qualified Miso.String as Miso
data Model
= Model
deriving ( Eq )
data Action
= ComboBoxEnter !Miso.MisoString
| NoOp
deriving (Show, Eq)
main :: IO ()
main =
Miso.startApp App
{ initialAction = NoOp
, model         = Model
, update        = Miso.fromTransition . updateModel
, view          = viewModel
, events        = Miso.defaultEvents
, subs          = []
, mountPoint    = Nothing
}
updateModel :: Action -> Transition Action Model ()
updateModel action = case action of
NoOp -> pure ()
ComboBoxEnter _str -> pure ()
viewModel :: Model -> View Action
viewModel _m =
select_ [ onInput ComboBoxEnter ]
[ option_ [] [ text …
```

Fix onInput regression on select elements + onChange

---

ghcjs-src/Miso/Html/Internal.hs
ghcjs-src/Miso/String.hs

Numbers were converted to `MisoString`s through regular `String`s. With `ToMisoString` instances for numbery things, this is really low hanging fruit.
More performance! Woo! :D

ToKey instances now use toMisoString

---

ghcjs-src/Miso/Util.hs

#308
The `disableIf` function mentioned in that issue is redundant now that the `disabled_` function takes a `Bool`.

Util functions withFoldable and conditionalViews

---

ghc-src/Miso/Html/Internal.hs
ghcjs-src/Miso/Html/Internal.hs
jsbits/diff.js
jsbits/isomorphic.js

Alright, I'm really enthusiastic about this. This PR enables this example:
https://fptje.github.io/miso-jswidget-example/
(Repository here: https://github.com/FPtje/miso-jswidget-example)
That's a [flatpickr](https://flatpickr.js.org/) widget, acting like it's been written in Miso instead of Javascript. You can click on the dates in the calendar, and the rest of the Miso app will update. You can click the Miso buttons and the widget will update. And there's a `toggle calendar visibility` button to prove that it plays nicely with Miso's diffing algorithm.
This kind of stuff was technically *possible* before, but with this PR, we can be **good** at it. This could be a *huge* selling point! It opens Miso up to a whole world of widgets that have already been made by other people. I'm …

Lifecycle events

---

ghcjs-src/Miso.hs
ghcjs-src/Miso/Effect.hs
ghcjs-src/Miso/Html/Internal.hs
ghcjs-src/Miso/Types.hs

As mentioned in https://github.com/dmjio/miso/pull/362#issuecomment-369561451 this slight generalization of `Effect` gives users the power to dispatch actions to the `update` function at their own discretion.
The most pressing use-case is scheduling an IO computation which creates a 3rd-party JS widget which has an associated callback. The callback can then call the sink to turn events into actions. To do this
without accessing a sink requires going via a subscription which introduces a leaky-abstraction. [Here's an example](https://github.com/basvandijk/miso-jswidget-example/commit/421b63f12fd9c14e5fc0ed588b265e4b08ae9b79).
Speaking of subscriptions, this generalization of `Effect` can actually supersede subscriptions. For example we can replace:
```haskell
mouseSub :: ((Int,Int) -> …
```

Allow scheduled IO computations access to a sink

---

ghcjs-src/Miso.hs
ghcjs-src/Miso/Effect.hs
ghcjs-src/Miso/Html/Internal.hs
ghcjs-src/Miso/Subscription/History.hs
ghcjs-src/Miso/Subscription/Keyboard.hs
ghcjs-src/Miso/Subscription/Mouse.hs
ghcjs-src/Miso/Subscription/SSE.hs
ghcjs-src/Miso/Subscription/WebSocket.hs
ghcjs-src/Miso/Subscription/Window.hs
ghcjs-src/Miso/Types.hs

Here's a more radical idea: let's get rid of the `getModel :: IO model` action from `Sub`.
We don't have any subscriptions nor examples which use the `getModel` action so I think it's better to remove it until we have a clear use-case.
This simplification allows `Subs` to be scheduled from the `update` function using `scheduleSub` or `effectSub`.

 Remove the 'IO model' argument of Sub 

---

tests/diff.test.js

This ensure DOM nodes were swapped properly.

Add more testing on swap case

---

ghc-src/Miso.hs
ghcjs-src/Miso.hs
ghcjs-src/Miso/Delegate.hs
ghcjs-src/Miso/FFI.hs
miso.cabal
src/Miso/Util.hs

I made the mistake in #355 to leave out the ghc side of Miso in the helper functions. I've moved them over to a new module `Miso.Helpers`, which is shared by both `ghc` and `ghcjs`. 
Since `Miso.Util` still exports the functions, it's backwards compatible.
Tests: I compiled and ran my isomorphic example, with one of the helpers shoehorned in somewhere to make sure that it works on both ghc and ghcjs.

Moved withFoldable and conditionalViews

---

ghcjs-src/Miso.hs
ghcjs-src/Miso/Html/Internal.hs
jsbits/delegate.js

Fixes #363 
This is a really simple solution. When you create an event related callback, put it in the list. Right before diffing everything in the list is released. They're safe to release, since the view function recreates them.
Tested with my components example and the jswidgets example.

Register event related callbacks and clear them right before diffing

---

ghcjs-src/Miso.hs
jsbits/delegate.js

I've tested it with the components and widgets example, also making sure that `currentCallbacks` and `oldCallbacks` have the right data at the right times.
With this patch no callback will be called after they've been released.

Releasing callbacks: Release proper callbacks

---

ghcjs-src/Miso/Effect.hs
ghcjs-src/Miso/Types.hs
tests/Main.hs

`mapAction` and `mapSub` are handy when nesting components.
Maybe we should bikeshed over the names a bit because I didn't think too long about it.

Add mapSub and mapAction

---

ghcjs-src/Miso/Types.hs

Besides `scheduleIO_` I also use the following in my own code:
```haskell
scheduleIOMaybe :: IO (Maybe action) -> Miso.Transition action model ()
scheduleIOMaybe io = Miso.scheduleSub $ \sink -> do
mbAction <- io
for_ mbAction $ \action ->
sink action
```
I didn't include that in this PR because I haven't found a satisfying name yet...

Add scheduleIO_ :: IO () -> Transition action model ()

---

README.md

In `miso-0.12.0.0`, `Int` is not an instance of `ToMisoString`, thus the example app is not compilable as:
```
No instance for (ToMisoString Model) arising from a use of ‘ms’
In the first argument of ‘text’, namely ‘(ms x)’
In the expression: text (ms x)     
In the second argument of ‘div_’, namely
‘[button_ [onClick AddOne] [text "+"], text (ms x),
button_ [onClick SubtractOne] [text "-"]]’
```

Upgrade Miso to make the example compilable

---

ghc-src/Miso/Html/Internal.hs
ghcjs-src/Miso/Html/Internal.hs

cc @cocreature @danburton
Appears the latest `servant` introduced a breaking change on the `HasLink` typeclass definition. Per @DanBurton's issue #426, adding an additional type variable, and parameter to `toLink`, appears to have fixed the issue. This patch should fix the stack build in https://github.com/commercialhaskell/stackage/issues/3750 as well.

Add CPP for new MkLink

---

ghc-src/Miso.hs
ghcjs-src/Miso/Subscription/WebSocket.hs
miso.cabal
src/Miso/WebSocket.hs

This allows sharing these types between the client and the server
which is often useful since the action type is usually also shared and
includes a constructor of the form `HandleMessage (WebSocket Message)`
which references the `WebSocket` type.
fixes #430

Move WebSocket related types to Miso.WebSocket

---

jsbits/delegate.js

For inputs of type checkbox, selections do not apply and should return
null. Safari throws a type error. This code checks for that condition
to ensure an error is not thrown. cc @tysonzero

Safari checkbox selection bug fix

---

src/Miso/Router.hs

This purpose of this instance is pretty much solely for route/handler sharing between client and server. As the client will just always receive "Nothing" for the header whilst the server will receive the real header value, whereas before the client would refuse to compile the code at all.

Add HasRouter instance for Header

---

frontend-src/Miso/String.hs
ghc-src/Miso/String.hs

This is a bit of a discussion starter. When working on the isomorphic consecutive text thing I noticed my view code still had `show` in it. In the frontend we've added `ToMisoString` instances to `Float`, `Double`, `Int` and `Word`. I couldn't change the code to use `toMisoString` directly though, as the server would fail on missing instances.
This implementation should pretty much give the same behavior as the frontend.

Add Float, Double, Int and Word instances to backend ToMisoString

---

frontend-src/Miso/Html/Internal.hs

It's an easy trap to fall for, using the onCreate / onDeleted events without keys.
The diffing algorithm will not notice that a node is different if it has the same tag and key (`undefined`) as the previous node. That will cause such events not to be called.

Warn people to use keys with lifecycle events.

---

jsbits/isomorphic.js
tests/diff.test.js
tests/package.json

- Based on https://github.com/dmjio/miso/pull/309 (CC @cocreature)
- Rebased on latest (and greatest) master
- Created tests for isomorphism (within diff.test.js, can change if desired)
Test report:
Note: When running `npm test` I got the following error:
```
SecurityError: localStorage is not available for opaque origins
```
After some Googling I found you need to set `"testURL": "http://localhost/"` in a jest config file, which is then passed to the `./node_modules/.bin/jest --config jestconfig.json` command. This change is not included in this PR as it might be caused by the version of jest I'm running.

Isomorphism: Fix consecutive text nodes causing an error

---

README.md

Especially the latest `miso-0.21.2.0` has an meaningful fix in `diff.js`.

Bump the Nix example to 0.21.2.0

---

frontend-src/Miso.hs
ghcjs-ffi/Miso/FFI.hs
jsaddle-ffi/Miso/FFI.hs
jsbits/isomorphic.js
tests/diff.test.js

Fixes mountpoint throwing an error when working with the `miso` function
Fixes #455
Also created a test to prevent future breaking
I actually just found out that there was already an implementation mentioned in the issue. This PR is somewhat more up to date and defines a test case.

copyDOMIntoVTree: take mountpoint into account

---

src/Miso/Html/Property.hs

Fix the following error when compiling miso:
```
$ nix-build
...
Building source dist for miso-0.21.2.0...
Preprocessing library miso-0.21.2.0...
Source tarball created: dist/miso-0.21.2.0.tar.gz
running tests
haddockPhase
installing
post-installation fixup
[ 8 of 21] Compiling Miso.Html.Event  ( src/Miso/Html/Event.hs, dist/build/Miso/Html/Event.o )
[ 9 of 21] Compiling Miso.Html.Property ( src/Miso/Html/Property.hs, dist/build/Miso/Html/Property.o )
src/Miso/Html/Property.hs:391:31: error:
• Variable not in scope: (<>) :: [Char] -> MisoString -> MisoString
• Perhaps you meant one of these:
‘<$’ (imported from Prelude), ‘<$>’ (imported from Prelude),
‘*>’ (imported from Prelude)
Perhaps you want to add ‘<>’ to the import list in the import of
‘Miso.String’ …
```

fix missing import

---

tests/diff.test.js

Should test MathML, bring `diff.js` back to 100% coverage.

Add test for MathML node

---

README.md

The command for live reload example is wrong:
ag -l | entr 'cabal build'
In above command it thinks that `cabal build` is an executable so it fails with error:
entr: exec cabal build: No such file or directory

Fix live reload entr command example in readme

---

README.md

Results in compilation errors. Surely because they are just copied from the Sample application above.

Fix the transition application

---

jsbits/isomorphic.js

This syntax breaks hjsmin, which is needed for minification before cross-compilation.

Remove default parameter values.

---

frontend-src/Miso.hs
frontend-src/Miso/Effect.hs
frontend-src/Miso/Types.hs
ghcjs-ffi/Miso/FFI.hs
jsaddle-ffi/Miso/FFI.hs

@dmjio is this the kind of docs you're looking for? Maybe this kind of trivial docs are not really useful for people forged by the fire of web platform, but for someone like me (relatively inexperienced in web development) it would be useful :)
Also there are bunch of functions exported from Miso module, about which I have no idea as to their purpose, like callbackToJSVal, objectToJSVal, ghcjsPure, swapCallbacks, releaseCallbacks, registerCallback. I'll dive into the source code and hopefully understand their usefulness. I'd like to add some short code examples to illustrate the usage of some non-obvious functions.

Improve haddock coverage of things exported from Miso module

---

jsbits/delegate.js

Search child nodes for a matching domRef, break loop when found. Prevents needless recursion.

Exit loop when child found

---

jsbits/delegate.js

`domRef` equality check is redundant, and can be removed.

Remove redundant equality check

---

sample-app-jsaddle/shell.nix

I think this is a better way to provide `reload` script in nix-shell environment. Even though technically speaking I see nothing bad about the old way I think this one is more idiomatic nix way of accomplishing it. Advantage is that with this change the script is created (and cached) in nix store though for something as simple as this it doesn't matter that much.

jsaddle example: better reload script

---

frontend-src/Miso/String.hs
ghc-src/Miso/String.hs

WIP: don't merge yet
This partly addresses #492. Essentially, I created a new 'FromMisoString' class that has a 'fromMisoStringEither' function that tries to read a MisoString into an Either String a. Still todo: 
1. for ghcjs I added a 'jsStringToDoubleEither' function whose function it is to try to parse double. The current implementation is kind of silly, as it just directly uses 'jsStringToDoubleEither' and wraps it in a 'Right'. Clearly, that is not yet the right thing to do. (But I will have to figure out how to do the right thing there). 
2. Trying to parse a, say Int, from a nonsensical string the error returned in the Left is now simply "Prelude.read: no parse". Maybe we want a better (= more specific) message there.
3. Update docs where necessary.
Before going through those …

split off a FromMisoString class from the ToMisoString class ( adresses #492)

---

README.md

Command as written in README causes erroneous behavior:
```
[nix-shell:~/]$ nix-shell -A env --run 'cabal configure --ghcjs && cabal build`
>
```
After edit to command, desired behavior occurs:
```
[nix-shell:~/]$ nix-shell -A env --run 'cabal configure --ghcjs && cabal build'
'cabal.project.local' file already exists. Now overwriting it.
Build profile: -w ghcjs-8.6.0.1 -O1
In order, the following would be built (use -v for more details):
...
```

Fix error in code in README.md

---

jsbits/diff.js

In the case where the old and new vdom have the same value, don't assume the UI control state has the same value. Only relevant for `checked` and `value` (potentially others).

Always update checked and value when diffing props.

---

examples/miso-examples.cabal
jsbits/delegate.js
miso.cabal

Safari throws a TypeError when selection* is indexed on a DOM node. This PR checks for that case and ignores it.

Check for input type before event accumulation.

---

default.nix

Among other things, this makes it possible to build Miso for multiple
platforms with Hydra.

Support some pass-through nixpkgs arguments.

---

jsaddle-ffi/Miso/FFI.hs

The github issue  #597 explains the rationale.
The gist is that sync functions don't work in jsaddle+Firefox and
miso doesn't need a sync function here, async is fine.

Make miso+jsaddle work under Firefox

---

.travis.yml
README.md
examples/canvas2d/Main.hs
examples/compose-update/Main.hs
examples/file-reader/Main.hs
examples/haskell-miso.org/client/Main.hs
examples/mario/Main.hs
examples/mathml/Main.hs
examples/router/Main.hs
examples/sse/client/Main.hs
examples/svg/Main.hs
examples/three/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
examples/xhr/Main.hs
exe/Main.hs
frontend-src/Miso.hs
frontend-src/Miso/Html/Internal.hs
frontend-src/Miso/Types.hs
ghc-src/Miso/Html/Internal.hs
ghcjs-ffi/Miso/FFI.hs
jsaddle-ffi/Miso/FFI.hs
jsbits/isomorphic.js
jsbits/util.js
sample-app-jsaddle/Main.hs
sample-app/Main.hs
tests/diff.test.js

@niteria @FPtje @tysonzero 
This preserves the isomorphism between the DOM and HTML by normalizing both structures by collapsing sibling text nodes. It should* solve the "consecutive text node" problem during pre-rendering.
Solves #589 #520 .

Collapse sibling text nodes.

---

frontend-src/Miso/Html/Internal.hs
ghc-src/Miso/Html/Internal.hs
src/Miso/Html.hs
src/Miso/Html/Element.hs

This addresses #596
Test Plan: Run https://github.com/niteria/miso-isomorphic-example/tree/vtextraw
which uses style_ and script_.
The browser console prints "Successfully prendered page" with no errors.
Going between / and /flipped successfully toggles the color of the buttons.

Add style_ and script_

---

jsaddle-ffi/Miso/FFI.hs

Async function breaks event prevent default and more in jsaddle mode. This changes the async function to a synchronous function.

Change Delegate Event to use Synchronous Function

---

default.nix
nix/default.nix

I have my own pkgs instance, then I want to use miso as part of my monorepo example. Since miso uses its own nixpkgs instance, my pkgs' config option is not recognized especially about `allowBroken` and `allowUnfree`. Be able to add these two options works in my case.

Make config options in miso's pkgs instance configurable

---

examples/haskell-miso.org/haskell-miso.cabal
examples/haskell-miso.org/shared/Common.hs

Accidentally noticed that https://haskell-miso.org/ Bulma nav was broken in mobile. Just added a div around the a-elements and moved classes to the div and now it works nicely. Tried to match the layouting with the original, but not sure what is happening in there.

Fixed Bulma nav for haskell-miso.org mobile

---

sample-app-jsaddle/default.nix
sample-app-jsaddle/shell.nix
sample-app/default.nix

Hi, I just upgraded my Project (which I originally started based on sample-app-jsaddle) from 1.6 to 1.7.1 and noticed that, for me, the change to shell.nix resulted in an error like "could not find main" when I run nix-shell --run reload. The url and sha256 in default.nix was still pointing to a tarball for 1.6, so I had to fix that.
These files are what is working for me now.

fix sample app .nix files for 1.7.1

---

.github/workflows/main.yml
exe/Main.hs
ghcjs-src/Miso/String.hs
miso.cabal
src/Miso/FFI.hs
src/Miso/Html/Types.hs
src/Miso/Subscription/WebSocket.hs

This allows HTML to be fetched at runtime and rendered into the DOM, by way of the virtual DOM.
This works by accepting a raw string as HTML, then lexing it with `tagsoup` and parsing it w/ `parsec` into a `View a`. At this point `diff.js` takes over and constructs raw DOM nodes from the original HTML given.
```haskell
view = div_ [] [ rawHtml "<div>hey</div>" ]
```
will expand into
```haskell
view = div_ [] [ div_ [] [ "hey" ] ]
```
at runtime.

Add rawHtml node.

---

.github/workflows/main.yml

Linker errors on GH cloud servers, yet not locally.

Remove OSX build from CI.

---

default.nix
examples/haskell-miso.org/default.nix
examples/sse/default.nix
nix/haskell/packages/ghc865/default.nix
nix/haskell/packages/ghcjs/default.nix
nix/haskell/packages/source.nix
nix/nixpkgs.json
nix/overlay.nix
sample-app-jsaddle/default.nix
sample-app-jsaddle/shell.nix

This reverts commit f910593c1a0a6ce1624f41d4e74963370cec958c.
Postpone this until performance regressions have been addressed 
https://github.com/ghcjs/ghcjs/issues/821

Revert "Move to ghcjs8107. (#682)"

---

src/Miso/FFI.hs
src/Miso/Html/Types.hs

Without this patch, we have
```
$ cabal build --constraint='text >=1.2.5'
src/Miso/FFI.hs:95:35: error:
Ambiguous occurrence ‘elem’
It could refer to
either ‘Prelude.elem’,
imported from ‘Prelude’ at src/Miso/FFI.hs:14:8-15
(and originally defined in ‘Data.Foldable’)
or ‘Miso.String.elem’,
imported from ‘Miso.String’ at src/Miso/FFI.hs:67:1-28
(and originally defined in ‘Data.Text’)
|
95 |   classSet <- ((JSS.pack "class") `elem`) <$> listProps obj
|                                   ^^^^^^
```
where `elem` [was added](https://hackage.haskell.org/package/text-2.0.1/changelog) to `Data.Text` in 1.2.5.0.

Fix GHC build with `text >=1.2.5`

---

src/Miso/FFI.hs

Despite the fact `elem` is being hidden, GHC 9.0.2 is upset. 
```
src/Miso/FFI.hs:95:35: error:
Ambiguous occurrence 'elem'
It could refer to
either 'Prelude.elem',
imported from 'Prelude' at src/Miso/FFI.hs:14:8-15
(and originally defined in 'Data.Foldable')
or 'Miso.String.elem',
imported from 'Miso.String' at src/Miso/FFI.hs:67:1-28
(and originally defined in 'Data.Text')
|
95 |   classSet <- ((JSS.pack "class") `elem`) <$> listProps obj
```

Use Prelude.elem explicitly in FFI.hs

---

examples/haskell-miso.org/shared/Common.hs

- Adds [2048](https://2048.haskell-miso.org) to [haskell-miso.org](https://haskell-miso.org)

Make 2048 an example on the website.

---

src/Miso/Html/Types.hs

It seems miso does not compile with GHC 9.8, this PR fixes that. 
Admittedly, since the upstream version of jsaddle also does not compile with 9.8 you currently also need something along the lines of 
```
packages:
.
source-repository-package
type: git
location: git@github.com:noinia/jsaddle.git
subdir: jsaddle
tag: e034fd40cd07c23ad85f3b059e8e3d8b698e322a
package miso
flags: +jsaddle
```
in your cabal.project (the only change in that repo w.r.t stock jsaddle is to get rid of the JavaScriptFFI language extention, which is deprecated/does nothing anyway)

import MkLink and ToLink from HasLink class (fixes build with ghc 9.8)

---

README.md

The URL of the Pixel Card Wars game was down (this was the staging URL). Change the link to use the production URL.
Click on the new link, witness it works.

Update Pixel Card Wars' URL to the production one

---

src/Miso.hs

Expose global sink

---

src/Miso/FFI.hs
src/Miso/Html/Types.hs
src/Miso/Subscription/History.hs
text-src/Miso/String.hs

https://hackage.haskell.org/package/text-2.1.2/changelog
We need to deal with `show` now being exported from `Data.Text`.
Strictly speaking, all old versions of Miso need a Hackage revision setting `text < 2.1.2`.

Fix build with `text` 2.1.2

---

README.md
docs/Internals.md

Per some discussions, users were curious about the internals and general flow of things

Add Internals.md documentation.

---

src/Miso/FFI.hs
src/Miso/Html/Types.hs
src/Miso/Subscription/History.hs
text-src/Miso/String.hs

Hides external API changes (`show` re-export) for `Data.Text`

Hide `show` re-exports on text > 2.1.2 in Miso.String

---

examples/canvas2d/Main.hs
examples/file-reader/Main.hs
examples/three/Main.hs

Brings in https://github.com/dmjio/miso/pull/740, adds CPP for ghcjs.

New syntax support, backwards compat cpp for ghcjs

---

src/Miso.hs

The initial `model` already exists in `App`

Remove duplicate model param.

---

haskell-miso.org/server/Main.hs

See https://downloads.haskell.org/~ghc/9.0-latest/docs/html/users_guide/9.0.1-notes.html.

Fix type application parse error on GHC 9+

---

src/Miso/Runner.hs

The `jsaddle-warp` support added in #768 uses the `run` function.
While working on [similar support](https://github.com/tweag/ghc-wasm-miso-examples/pull/23) previously, I found that `debug` is much more useful than `run` in practice due to supporting live reloading, but it's meant to be used in GHCI, and with `cabal run` it just exits. With this PR, we use `debug` if and only if we're in GHCI. Matching on `"<interactive>"` is a bit ugly, but it's the only way I know of detecting this.
Most usefully, with this change, it's possible to use a command like `ghcid -c 'cabal repl simple' -Wr` for reloading on file save, or, if you're feeling fancy, `ghcid -c 'cabal repl --enable-multi-repl simple miso' -W -T Main.main`. This is _particularly_ nice with something like #749, which I'll try to …

Use `JSaddle.Warp.debug` when run from GHCI

---

.github/workflows/main.yml
default.nix
examples/wasm-hello-world/Main.hs
nix/default.nix
nix/wasm/default.nix

- Pull in ghc-wasm-meta flake
- Create builder (in the spirit of .jsexe) for wasm compiler
- Create hello-world-wasm-web, put under CI
- Add wasm overlay for our own purposes
- Pulls in the latest version of node

Add wasm overlay, put hello-world-wasm-web under ci.

---

haskell-miso.org/shared/Common.hs

Didn't want to make a whole issue for such a minor change but the recent move of the haskell-miso.org source to the top-level directory broke the website's link to its source code. This fixes the issue.

Fix broken source link on haskell-miso.org

---

nix/nixpkgs.json

Currently points to our nixpkgs fork with a `https://` ghcjs URL instead of a non-working `git://` URL. Technically can cheekily be switched back to non-fork as long as it's been well cached to avoid depending on a fork.

Upgrade nixpkgs to version with fixed ghcjs

---

jsbits/delegate.js

In some rare circumstances `event.target` can be `null` if diffing has removed a DOM node before an event handler is invoked. This can occur with high load events like mouse*. This check avoids null reference exceptions during delegation.
@brakubraku

Ensure that target exists before delegation.

---

examples/components/Main.hs
jsbits/delegate.js
jsbits/isomorphic.js
src/Miso.hs
src/Miso/Effect.hs
src/Miso/FFI.hs
src/Miso/Html/Types.hs
src/Miso/Internal.hs
src/Miso/Subscription/History.hs
src/Miso/Subscription/Keyboard.hs
src/Miso/Subscription/Mouse.hs
src/Miso/Subscription/SSE.hs
src/Miso/Subscription/WebSocket.hs
src/Miso/Subscription/Window.hs
src/Miso/Types.hs

- Create 'ComponentState' to house component lifetime
- Add top-level 'unmount' function
- Remove duplicate calls to 'sink'
- Kill all threads associated with a 'Sub' on component unmount.
- Add example to component to show Sub cleanup
- Sink initial action after forking event loop 
- Remove `BlockedIndefinitelyOnMVar` hack (now that we store `Sink action` in a global `IORef`
- Use proper mount points, document top-level functions w/ mounting.
- Move `type Sink a = a -> IO ()` to `type Sink a = a -> JSM ()`

Cleanup Subs

---

examples/todo-mvc/Main.hs
examples/websocket/Main.hs
src/Miso/Event/Types.hs
src/Miso/Html/Event.hs

For performance reasons its good if we don't listen on all mouse / drag events. It's best if users add these incrementally to their applications. This should reduce congestion in the event queue.
cc @georgefst @brakubraku

Split out events.

---

src/Miso/Types.hs

- This avoids UndecidableInstances

Use a different HasLink instance for View.

---

haskell-miso.org/server/Main.hs
haskell-miso.org/shared/Common.hs
src/Miso/Subscription/History.hs

- Renames 'go' prefix to 'uri' for haskell-miso.org URIs
- Normalizes URI for client and server
- Fixes a bug where current page is not highlighted in nav
- All pages are now isomorphisms between the DOM and the VDOM

Normalize URI, drop prefix slash when parsing window.location.href

---

src/Miso/Render.hs

Drop trailing bytes when rendering attributes

---

examples/components/Main.hs
examples/router/Main.hs
examples/simple/Main.hs
examples/sse/shared/Common.hs
examples/svg/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
examples/xhr/Main.hs
src/Miso/Effect.hs
text-src/Miso/String.hs

- Refactor examples to take advantage of fixity changes
- Use defaultApp smart constructor with examples
```haskell
-- dmj: bind tightest to the `model` portion
infixl 0 <#
infixr 0 #>
```
This allows convenient syntax like
```haskell
m { uri = newUri } <# NoOp <$ pushURI u
```
and
```haskell
m - 1 <# consoleLog "substracting" >> pure NoOp
```
with requiring parens

Add fixity for (<#) (#>) combinators

---

examples/sse/sse.cabal

- Use `common-modules` for `Common`

Upgrade SSE example to use cabal-version 2.2

---

src/Miso/Effect.hs

- Indent `Combinators` in haddock
- Move `Transition` to top
- Various typos

Properly indent haddocks for Effect.

---

examples/components/Main.hs
jsstring-src/Miso/String.hs
miso.cabal
sample-app/Main.hs
src/Miso.hs
src/Miso/Exception.hs
src/Miso/FFI.hs
src/Miso/Internal.hs
text-src/Miso/String.hs

- Allows child components to sample a parent component's state
- Saves each component's local state into an `IORef` that gets updated during the event loop post-diffing.
- If the component being sampled is not currently mounted a `Nothing` is returned.
- Adds example usage of `sample` to components
- Consider `MonadFail` instead of `Maybe`

Allow Components to sample each other's local state.

---

examples/svg/Main.hs
haskell-miso.org/shared/Common.hs
jsbits/delegate.js
src/Miso.hs
src/Miso/Delegate.hs
src/Miso/Effect.hs
src/Miso/Event/Types.hs
src/Miso/FFI.hs
src/Miso/Html/Event.hs
src/Miso/Html/Types.hs
src/Miso/Internal.hs
src/Miso/Render.hs
src/Miso/Types.hs

- Checks that all event handlers defined are being listened for by top-level event delegation (local to the Component mount or top-level App mount).
- Adds a warning if an event that was raised did not find an event handler for dispatch.
- Fix detected bug (this feature already found a bug in the svg example). Adds "pointermove" to the top-level Events map
- Introduce 'Events' type (synonym for Map MisoString Bool)
- Adds DebugEvent and DebugAll
- Renames some ambiguous variables to be more descriptive.
- Passes event Map from App{..} into Event construct continuation.
~~- Adds `componentEvents` to `ComponentState`~~
- Renames P,E,S to Property, Event, Style.
This detects if an event, that a user is expecting to fire, is not being listened on by the top level event delegator DOM node …

Intitial commit of DebugEvents

---

examples/components/Main.hs
jsbits/diff.js
src/Miso/Exception.hs
src/Miso/Internal.hs

- Adds 'exception' handler to unify mounting exception handling
- Abstracts out vtree creation w/ 'createNode'
- Prefix FFI imports in Internal.hs
~~- Remove .querySelectorAll() checks in diff.js (perf)~~ (dmj: can't do this yet)

Invoke unmount / mount hooks in post mounting / unmounting phases.

---

examples/components/Main.hs
examples/sse/client/Main.hs
examples/sse/server/Main.hs
examples/sse/shared/Common.hs
haskell-miso.org/client/Main.hs
haskell-miso.org/server/Main.hs
haskell-miso.org/shared/Common.hs
src/Miso.hs
src/Miso/Internal.hs
src/Miso/Render.hs
src/Miso/Types.hs

- Makes `Component` dynamic
- Removes `startComponent`, `misoComponent`
- Removes type level `Symbol` `"name"` on `Component`

Make Component dynamic, remove Symbol parameterization

---

.github/workflows/main.yml
README.md
default.nix
examples/canvas2d/Main.hs
examples/components/Main.hs
examples/compose-update/Main.hs
examples/file-reader/Main.hs
examples/mario/Main.hs
examples/mathml/Main.hs
examples/router/Main.hs
examples/simple/Main.hs
examples/sse/shared/Common.hs
examples/svg/Main.hs
examples/three/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
examples/xhr/Main.hs
haskell-miso.org/shared/Common.hs
nix/haskell/packages/ghcjs/default.nix
nix/haskell/packages/source.nix
sample-app/Main.hs
src/Miso.hs
src/Miso/Event/Decoder.hs
src/Miso/Event/Types.hs
src/Miso/Html/Event.hs
src/Miso/Internal.hs
src/Miso/Subscription/Keyboard.hs
src/Miso/Types.hs

- `defaultApp` no longer takes `a`
- Refactor examples to account for optionality
- Updates third-party examples to support this (updates them w/ latest code too, e.g. `PointerEvent`)
- Puts third-party examples under CI
- `DebugEvent` should only be on optionally

Make initialAction optional

---

jsbits/isomorphic.js
tests/diff.test.js

- Adds 90%+ code coverage for `isomorphic.js`
```
---------------|----------|----------|----------|----------|-------------------|
File           |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
---------------|----------|----------|----------|----------|-------------------|
All files      |    98.48 |    96.65 |    96.97 |    98.38 |                   |
diff.js       |      100 |      100 |      100 |      100 |                   |
isomorphic.js |    96.03 |    91.76 |     87.5 |    95.83 | 30,49,198,199,200 |
---------------|----------|----------|----------|----------|-------------------|
```

Add move testing for the isomorphic integrity check.

---

nix/overlay.nix

- This is to avoid out of disk errors we're experiencing in CI
```
awsBox.......> error: preallocating file of 110741 bytes: No space left on device
```

Runs a garbage collect on each deploy

---

src/Miso/Internal.hs

In scenarios (like the `components` example) where deeply nested components undergo unmounting in rapid succession, a delay must be introduced to ensure that unmount actions are processed by the parent before the thread is killed. Otherwise, this can lead to scenarios where a middle child does not have enough time to process both the unmount action from its own child and the relaying of its unmount action to its parent.
Introducing a `threadDelay` will both buy us time and invoke the thread scheduler to ensure other thread stacks have time to evaluate thunks on their heaps before their own destruction (this includes thunks that write to parent sinks).
Tested on both JS and WASM (single threaded environments, and `-threaded` with `jsaddle-warp`)

Introduce 1ms delay during unmount.

---

jsbits/miso.js
src/Miso/FFI.hs
tests/default.nix

By removing `var` we keep `module` named `"module"` top-level and exported globally. It no longer gets GC'd in the WASM context. Also allows us to truly drop `window` usage from miso.js, and not use it in the FFI calls.

var module = module || {}; -> module = {};

---

jsbits/miso.js
src/Miso.hs
src/Miso/FFI.hs
tests/miso.spec.js

- Adds test for `callFocus()` / `callBlur()`
- Adds optional timeout defaults
- Moves document out of setBodyComponent haskell function and into the FFI call

Add code coverage for focus / blur utils.

---

tests/miso.spec.js

Ensure that `unmount` is getting called in the correct order. Uses diff to create and destroy the tree recursively, unmount calls are tracked during this process.

Add test for recursive component unmounting.

---

README.md
examples/canvas2d/Main.hs
examples/components/Main.hs
examples/file-reader/Main.hs
examples/mario/Main.hs
examples/router/Main.hs
examples/simple/Main.hs
examples/sse/server/Main.hs
examples/sse/shared/Common.hs
examples/svg/Main.hs
examples/three/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
examples/xhr/Main.hs
haskell-miso.org/shared/Common.hs
nix/haskell/packages/source.nix
sample-app/Main.hs
src/Miso.hs
src/Miso/Effect.hs
src/Miso/Internal.hs
src/Miso/Render.hs
src/Miso/Types.hs

- `Effect` is now `effect model action a`
- `App`, `update` and `Effect` reflect identical param order
- Drop `()` in `App` (make `a`)
- Update examples & third-party examples to reflect
- Correct type variable naming where applicable

Unify param ordering between Effect and App

---

examples/svg/Main.hs
nix/haskell/packages/source.nix
src/Miso/Event/Decoder.hs
src/Miso/Event/Types.hs

- `"x"` -> `"clientX"`
- `"y"` -> `"clientY"`
- Add `UnknownPointerType` (Spec says it can be unknown / empty string as well.)
- `coords` -> `client`, be spec. preserving

Update PointerEvent to use Double

---

nix/haskell/packages/source.nix

- Bumps https://2048.haskell-miso.org hash to latest

Bump 2048 hash

---

js/miso.js
js/miso.spec.js
src/Miso/Diff.hs
src/Miso/FFI.hs

Now that `jest-jsdom-environment` sets this up implicitly we no longer need to explicitly pass (`window`, `document`) to `diff`, etc. This simplifies the FFI statements in Haskell and the test code in `miso.spec.js`

Drop document window param

---

js/miso.js
js/miso.spec.js
package.json

- Prettier by default will strip quoted field names, `{"quoteProps": "preserve"}` changes this default behavior. This is necessary to get around closure compilation attempting to rename field names to the smallest possible names.
- Standardizes on single-quotes
- This PR introduced the feature we need to ensure sound closure compilation https://github.com/prettier/prettier/pull/5934

Preserve quoted field names during miso.js export

---

default.nix
nix/overlay.nix

- For use with nixpkgs upgrading.
- When we move to ghc9122, we'll need to keep around our old ops tools.

Try to pin our nixops.

---

src/Miso/Internal.hs
ts/miso.ts
ts/miso/dom.ts
ts/miso/event.ts
ts/miso/hydrate.ts
ts/miso/smart.ts
ts/miso/types.ts
ts/spec/component.spec.ts

- Refines`VTree` to `VComp | VNode | VText`
- Adjust `hydrate.ts` / `dom.ts` to reflect types (as cast)
- Adds smart constructor for `VComp` (`vcomp`)
- Removes unsafe `domRef: any` in favor of union `type DOMRef = HTML | SVG | MathML`
- Refines `vcomp` `tag` to `'div'` (always) and `domRef: HTMLElement` (always)
- Refines `domRef` to `Text` for `VText`
- Adjusts tests to use `vcomp` smart constructor
- Adds "ns" field for `VText`, Haskell side.
- Refines mount callback to `VComp` in `dom.ts`
- Factors out `preamble` function for pre-`walk` activities in `hydration.ts`
- Intros and exports `NS` type `'html' | 'svg' | 'mathml'`

Adds discriminated union for VTree (VComp | VNode | VText)

---

.github/workflows/main.yml
cabal.project
default.nix
examples/sse/default.nix
examples/sse/nix/machine.nix
haskell-miso.org/default.nix
nix/default.nix
nix/haskell/packages/ghc/default.nix
nix/haskell/packages/ghcjs/default.nix
nix/legacy/default.nix
nix/legacy/haskell/packages/ghc/default.nix
nix/legacy/haskell/packages/ghcjs/default.nix
nix/legacy/nixpkgs.json
nix/legacy/overlay.nix
nix/nixpkgs.json
nix/overlay.nix
nix/source.nix
nix/wasm/default.nix
shell.nix
src/Miso.hs
src/Miso/Exception.hs
src/Miso/Internal.hs
tests/Main.hs

📦 Introduce a multi-nixpkgs workflow (`legacyPkgs` and `pkgs`)
Because nixpkgs has removed `python27` we can no longer build `nixops` (it has also been removed, unfortunately). So until a new `nixops` comes onto the scene we must keep around our old nixpkgs for deployment (for now).
- Copy old `nix/` folder into `legacy/`, repurpose `nix/` to use `pkgsCross.ghcjs`
- Introduce `legacyPkgs` (`ghcjs86`, `closure-compiler`, `nixops-1.7`)
- Introduce recent `pkgs` (`ghcjs9122`, `bun`)
- Hoist `source.nix` to top-level (consumed by all), adjust paths accordingly
- Put new JS backend (`ghcjs9122`) `miso` build under CI
- Keep `deploy` script, `haskell-miso.org` and `sse` examples under `legacyPkgs`
- Use `doHaddock`
- Formatting of `nix`
- Update `cabal.project` to include new js backend dep. …

Multi-nixpkgs workflow

---

.github/workflows/main.yml
default.nix
haskell-miso.org/nix/nginx.nix
nix/legacy/overlay.nix

Add nginx NixOS test, --dry-run in CI.

---

examples/todo-mvc/Main.hs
src/Miso.hs
src/Miso/FFI.hs

Users have requested to be able to set CSS styles dynamically (in `<head>`) on initial application load.

Add addStyle, addStyleSheet.

---

examples/todo-mvc/Main.hs
src/Miso.hs
src/Miso/Html/Types.hs
src/Miso/Internal.hs
src/Miso/Render.hs
src/Miso/Types.hs

🍜 `App { styles :: [CSS] } `
====================
```haskell
main :: IO ()
main = run app { 
styles = [ Href "https://your-domain/style.css"
, Style "body { background-color: red; }" 
] 
}
app :: App Effect Model Action ()
app = defaultApp module update view
```
- Allow users to add `CSS` styles to top-level `App`.
- This allows users to adjust styles using hot-reload w/ `jsaddle`.
- Promotes 'addStyleSheet' and 'addStyle' to first class functions in App.
- Guarantees that style will be present before first page draw.
- Renames existing internal `Style` to `Styles`, we now claim `CSS (Style)` for the external API.
- Updates todo-mvc example to reflect this.
Previously `addStyle` and `addStyleSheet` would run on `initialAction` to append CSS to a page, but the downside of doing so was that …

Add top-level styles to App.

---

examples/file-reader/Main.hs
examples/miso-examples.cabal
src/Miso.hs
src/Miso/FFI.hs

- Use [miso-from-html](https://github.com/dmjio/miso-from-html) to process claude.ai generated bulma css
- Drop old FFI statements, port to `jsaddle`
- Update cabal file to support WASM and native workflows
- Use `Miso.Lens` for (info field)
- Test `import Miso` ergonomicity
- Use custom css `Style` and bulma cdn for `Href`
- Expose additional `Miso.FFI`, `syncCallback`, etc
- Drop `ghcjs-base`

Modernize file reader example, test ergonomics

---

src/Miso/Internal.hs

- This obviates the need for `threadDelay` since all events are processed before unmounting, in a synchronous callback.
- Let the GC recycle the component thread. Since `componentName` is deleted from the global `componentMap`, all references will go out of scope.

Fully drain event queue during synchronous unmount.

---

examples/canvas2d/Main.hs
examples/components/Main.hs
examples/fetch/Main.hs
examples/file-reader/Main.hs
examples/mario/Main.hs
examples/router/Main.hs
examples/simple/Main.hs
examples/sse/server/Main.hs
examples/sse/shared/Common.hs
examples/svg/Main.hs
examples/three/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
haskell-miso.org/nix/nginx.nix
haskell-miso.org/shared/Common.hs
nix/haskell/packages/ghcjs/default.nix
nix/legacy/haskell/packages/ghcjs/default.nix
nix/legacy/overlay.nix
nix/source.nix
sample-app/Main.hs
src/Miso.hs
src/Miso/Effect.hs
src/Miso/Internal.hs
src/Miso/Render.hs
src/Miso/Types.hs

- Introduce `EffectCore`
- Re-export `Effect` as synonym on `EffectCore`
- Drop two type variables on `App` and one on `Effect`.
- Drop `translate` function.
This was nice to add, but it does make the interface more intimidating, and not simple. So we'd like to keep it simple for newcomers. We can always add this back if there is a compelling use case for a custom monad (opposed to Effect).

Revert translate, keep interface simple, synonym Effect

---

src/Miso/FFI/Internal.hs
src/Miso/Fetch.hs

The first one is a basic correctness issue.
The second may look like it doesn't really matter, but it actually saved me from a tricky CORS issue. And AFAICT, there is really no point in adding the header when there's no actual content.

More fetch fixes

---

src/Miso/Fetch.hs

As discussed just now on Matrix.
For the type class, there's an argument for only exposing it through some internal module rather than from the top-level `Miso` module where it would clutter the haddocks with a pretty niche part of the API. I'll leave that up to @dmjio. Personally I'd seriously consider factoring out the whole fetch API in to a separate library, not tied to Miso, but that suggestion was, not unreasonably, firmly rejected.

Expose more of the fetch API

---

miso.cabal
src/Miso/FFI/Internal.hs

- This warning is related to Success not being exposed

Hide Success warning for all GHC JS

---

README.md

- Adds section on build output and hosting

Update JS backend docs quick start tutorial.

---

src/Miso/Router.hs

It seems that we need `PolyKinds` to make `HasRouter` working properly with servant endpoints such as `Verb`.

Adds PolyKinds to `Miso.Route` to make `Verb` working properly with HasRouter

---

README.md

Per feedback, we should ensure we're using miso's pinned nixpkgs for fetching ghcjs.

Updates JS backend nix instructions

---

README.md

- Describes how to use nix to install ghcjs on your system's global environment

Add global install instructions for ghcjs

---

src/Miso/Lens.hs

Slightly reduce import confusion, less code, benefit from more comprehensive docs in base :slightly_smiling_face: 
The operator has been available in base since base-4.11.0.0 which corresponds to ghc 8.4.1 which is well within the range of GHCs that miso aims to support.

Re-export <&> from base

---

README.md
cabal.project
miso.cabal

Minor cleanup:
- No need to pull in jsaddle-wasm via an `s-r-p`, it is on Hackage. Also add an appropriate lower bound (for the synchronous callbacks feature).
- The `time` bound relaxation isn't necessary anymore as most packages allow the more recent pre-installed `time` that supports Wasm.

Simplify Wasm-related `cabal.project` content

---

examples/fetch/Main.hs
examples/miso-examples.cabal
nix/wasm/default.nix

Fetch example is now agnostic to GHC backend

Drop js-only from fetch example

---

src/Miso/Svg/Element.hs

1. Removing all svg element helpers that are no longer listed on MDN website (on the other hand they are all mentioned as deprecated here: https://udn.realityripple.com/docs/Web/SVG/Element#Obsolete_and_deprecated_elements)
2. Adding one new helper (the only one we're missing from MDN's [SVG reference](https://developer.mozilla.org/en-US/docs/Web/SVG/Reference/Element)): `feDropShadow_`
3. Fixing typo in `feMorhpology_` -> `feMorpjology_`
4. Changing all the links to point directly to SVG/Reference on MDN (the original links we had redirect there anyway).

Remove deprecated, add newly introduced svg elements

---

examples/components/Main.hs
examples/mario/Main.hs
examples/router/Main.hs
examples/sse/shared/Common.hs
examples/todo-mvc/Main.hs
src/Miso/Lens.hs

Followup on https://github.com/dmjio/miso/pull/913 which deprecated bunch of functions and reexposed stuff from Control.Monad.State. Also noticed that all lens examples have an extraneous argument to Effect which should be removed.

Fix ghc warnings and type errors in haddocks

---

src/Miso/Svg.hs
src/Miso/Svg/Attribute.hs

Followup on https://github.com/dmjio/miso/pull/914
I went through https://developer.mozilla.org/en-US/docs/Web/SVG/Reference/Attribute and removed all the attributes for which the docs are no longer available or are explicitly marked as deprecated.

Remove deprecated and add newly introduced SVG attributes

---

miso.cabal
src/Miso/Svg.hs
src/Miso/Svg/Property.hs

In `miso` an `Attribute` is either an `Event`, `Property` or `Style`. In web nomenclature an Attribute lives as a key value pair on the HTML itself, and a Property lives on the DOM reference. `miso` normalises the two internally and exposes a unified `Property` abstraction. Therefore, the module names should reflect miso's abstraction. This change makes HTML and SVG modules consistently named and reflective of the `miso` `Attribute`.

Attribute -> Property

---

examples/fetch/Main.hs
examples/file-reader/Main.hs
examples/mario/Main.hs
examples/sse/server/Main.hs
examples/svg/Main.hs
examples/three/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
haskell-miso.org/server/Main.hs
haskell-miso.org/shared/Common.hs
miso.cabal
nix/source.nix
shell.nix
src/Miso.hs
src/Miso/Html/Element.hs
src/Miso/Html/Property.hs
src/Miso/Html/Types.hs
src/Miso/Property.hs
src/Miso/Style.hs
src/Miso/Style/Color.hs
src/Miso/Svg.hs
src/Miso/Svg/Attribute.hs
src/Miso/Svg/Element.hs
src/Miso/Util.hs

Addresses https://github.com/dmjio/miso/issues/746
@jhrcek

Adds Miso.Style

---

src/Miso/Property.hs

This was incorrectly typed per @jhrcek findings. It's technically not used anywhere else in the codebase, but others might be using it.

integerProp, Int -> Integer

---

README.md
examples/components/Main.hs
examples/fetch/Main.hs
examples/file-reader/Main.hs
examples/simple/Main.hs
examples/sse/server/Main.hs
examples/sse/shared/Common.hs
examples/svg/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
haskell-miso.org/shared/Common.hs
sample-app/Main.hs
src/Miso.hs
src/Miso/Internal.hs
src/Miso/Render.hs
src/Miso/Types.hs

This should crystallize / simplify the component feature.
- `App` is now parameterized by `name :: Symbol`, this allows `notify` and `sample` to be type safe during message passing and reading other component state. The `name` parameter is optional unless using the component feature (which means using `notify` / `sample`)
- `Component` is now used purely as an existential wrapper for `App`, when used w/ `notify_` / `sample_` its to indicate that the component is dynamically generated. The dynamically generated component can be communicated with now via its name, which is accessible via `ask` (per the `RWS` refactor).
- Introduces `notify_`, `sample_`,

Component refactor

---

src/Miso.hs
src/Miso/Effect.hs

Now that 'Effect' is defined in terms of 'RWS', the component name is available via 'ask'. This PR exposes 'componentId' as a primitive function.
The intended use case is when dealing with dynamically generated components that are not statically known. componentId will retrieve the dynamically set component ID.

Add componentId, synonym for ask in RWS.

---

README.md
examples/canvas2d/Main.hs
examples/components/Main.hs
examples/fetch/Main.hs
examples/file-reader/Main.hs
examples/mario/Main.hs
examples/mathml/Main.hs
examples/router/Main.hs
examples/simple/Main.hs
examples/sse/server/Main.hs
examples/sse/shared/Common.hs
examples/svg/Main.hs
examples/three/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
haskell-miso.org/client/DevelMain.hs
haskell-miso.org/shared/Common.hs
nix/source.nix
sample-app/Main.hs
src/Miso.hs
src/Miso/Effect.hs
src/Miso/Html/Event.hs
src/Miso/Html/Types.hs
src/Miso/Internal.hs
src/Miso/Render.hs
src/Miso/Types.hs

Now that `Component` has been added, and `Component` can be nested recursively, `App` is now subsumed by `Component`. This PR replaces `App` with `Component`.
- `App` ->`Component`
- `defaultApp` -> `defaultComponent`
- `startApp` -> `startComponent`
- `Component` -> `SomeComponent`
- `io`-> `io_`, `io_` -> `io`
- Update examples (third-party too)
- `notify_` -> `notify'`
- `sample_` -> `sample'`
- Add `batch_`
- `Text` -> `VText`
- `Node` -> `VNode`
- `TextRaw` -> `VTextRaw`

App -> Component

---

examples/components/Main.hs
examples/sse/server/Main.hs
haskell-miso.org/server/Main.hs
src/Miso/Internal.hs
src/Miso/Types.hs

Instead of using `SomeComponent` to indicate dynamic `Component` creation, it will be more user-friendly to use unit (`()`).

Add dynamic Component example

---

default.nix
examples/miso-examples.cabal
examples/three/Main.hs
nix/wasm/default.nix

Rewrite three.js example to use jsaddle, WASM-backend.

---

examples/components/Main.hs
examples/todo-mvc/Main.hs
src/Miso/Canvas.hs
src/Miso/Html/Element.hs
src/Miso/Html/Types.hs
src/Miso/Internal.hs
src/Miso/Mathml/Element.hs
src/Miso/Property.hs
src/Miso/Render.hs
src/Miso/Svg/Element.hs
src/Miso/Types.hs

`Key` has always existed as an explicit identifier internally, this change makes` Key` no different than any other 'Attribute'. User's can now set a `Key` inside of an `Attribute` list using 'key_'. This change is purely cosmetic for the Haskell interface, no TypeScript changes required. ~This preserves existing `trKeyed_`, `liKeyed_` combinators as well~
```haskell
-- example
keyedDiv = div_ [ key_ 1 ] []
```

Add key_, drop componentWith* variants.

---

README.md

`❯` gets in the way when using the clipboard button to paste into the terminal

Remove prompt symbol from ghcjs commands

---

src/Miso/Effect.hs

Since `Transition` was a synonym for `StateT model (Writer action)` let's synonym the "new" `Transition` (aka `Effect`) as `RWS`.
If this compiles it should give us the `Zoom` instances for @noinia in #953

Drop EffectCore, synonym Effect as RWS.

---

README.md
miso.cabal
src/Miso.hs
src/Miso/Event/Types.hs
src/Miso/FFI.hs
src/Miso/FFI/Internal.hs
src/Miso/Html/Event.hs
src/Miso/Html/Property.hs
src/Miso/Media.hs

Fleshes out media API, generalizes to support video as well.
cc @juliendehos

Miso.Media 🔊 🎥

---

miso.cabal
src/Miso/Util/Lexer.hs

Adds a lexer that operates on `MisoString` in `Utils/` submodules. This employs the "maximal munch" rule, as seen in the `Alternative` instance
This will be useful for creating lexers, parsers, and QQs, that operate on HTML (jsx-esque), CSS, URIs.

Add Miso.Util.Lexer

---

examples/components/Main.hs
src/Miso/Internal.hs

This avoids unnecessary polymorphism when using the global variable trick.

Revert `subKey` polymorphism.

---

examples/simple/Main.hs
miso.cabal
src/Miso/Internal.hs
src/Miso/Style.hs
src/Miso/Style/Color.hs
src/Miso/Style/Types.hs
src/Miso/Types.hs

```haskell
testSheet :: StyleSheet
testSheet =
sheet_
[ selector_ ".name"
[ backgroundColor red
, alignContent "top"
]
, selector_ "#container"
[ backgroundColor blue
, alignContent "center"
]
, keyframes_ "slide-in"
[ "from" =:
[ transform "translateX(0%)"
]
, "to" =:
[ transform "translateX(100%)"
, backgroundColor red
, backgroundSize "10px"
, backgroundRepeat "true"
]
, pct 10 =:
[ "foo" =: "bar"
]
]
]
```
```bash
λ> putStrLn $ MS.unpack (renderStyleSheet testSheet)
.name {
background-color : rgba(255,0,0,1.0);
align-content : top;
}
#container {
background-color : rgba(0,0,255,1.0);
align-content : center;
}
@keyframes slide-in {
from {
transform : translateX(0%);
}
to {
transform : translateX(100%);
background-color : rgba(255,0,0,1.0);
background-size : 10px;
background-repeat : …
```

Add `@keyframes` animation and `@media` query support to `Miso.Style`

---

miso.cabal
src/Miso.hs
src/Miso/State.hs

This is done to clean up `src/Miso.hs` re-export list. Also serves as a placeholder to add new combinators (unrelated to lenses).

Add `Miso.State`

---

src/Miso/FFI.hs

dmj: This is useful for native FFI.

Export `asyncCallback1`, `asyncCallback2` from `Miso.FFI.Internal`

---

ts/spec/dom.spec.ts

Since the key and value were identical in the tests, the bug in #990 went undetected.
This PR changes the test corpus data so the keys and values are no longer identical.

Update test for attribute removal.

---

cabal.project
miso.cabal
src/Miso.hs

Motivated by https://github.com/tweag/ghc-wasm-miso-examples/issues/33
Depends on https://github.com/amesgen/jsaddle-wasm/pull/26, released in jsaddle-wasm 0.1.2.0

Don't use JS `eval` on Wasm

---

README.md
examples/canvas2d/Main.hs
examples/components/Main.hs
examples/fetch/Main.hs
examples/file-reader/Main.hs
examples/mario/Main.hs
examples/mathml/Main.hs
examples/router/Main.hs
examples/simple/Main.hs
examples/sse/client/Main.hs
examples/svg/Main.hs
examples/three/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
haskell-miso.org/client/Main.hs
nix/source.nix
sample-app/Main.hs
src/Miso.hs

We must do this or we can potentially run into recursive component mounting issues. This is a breaking change, as it will force users to annotate their top-level components with a type-level `Symbol`.
We need this to allow `notify` and `sample` on the root component in an explicit way. cc @Zer0-

Enforce component naming at top-level

---

README.md
examples/canvas2d/Main.hs
examples/components/Main.hs
examples/fetch/Main.hs
examples/file-reader/Main.hs
examples/mario/Main.hs
examples/mathml/Main.hs
examples/router/Main.hs
examples/simple/Main.hs
examples/sse/client/Main.hs
examples/sse/server/Main.hs
examples/sse/shared/Common.hs
examples/svg/Main.hs
examples/three/Main.hs
examples/todo-mvc/Main.hs
examples/websocket/Main.hs
haskell-miso.org/shared/Common.hs
miso.cabal
nix/source.nix
sample-app/Main.hs
src/Miso.hs
src/Miso/Concurrent.hs
src/Miso/Effect.hs
src/Miso/Event.hs
src/Miso/Exception.hs
src/Miso/Internal.hs
src/Miso/Lens.hs
src/Miso/Render.hs
src/Miso/Types.hs

:artificial_satellite: Pub / Sub 📡  / Mailboxes 📬 
============
Per chats with @kaol in #1000, while `Component` are now completely isolated due to the existential type encoding, `Component` communication is not. Currently `notify` and `sample` require type-level unification on either `action` or `model`.
This has practical implications for module dependencies, and `Component` sharing, which make usage unwieldy at times (as noted in #1000)
This PR is a complete overhaul of `Component` communication, aimed at preserving isolation of `Component`, yet allowing for intra & inter-`Component` communication with `publish`, `subscribe`, `unsubscribe` primitives via a user-defined JSON protocol.
This PR aims to implement a variant of the original Elm mailbox system pioneered by @evancz. Under the …

Add `Pub`/`Sub` system for `Component` communication 📡 

---

src/Miso/Canvas.hs

Currently, we have something like this:
```hs
draw :: Canvas ()
draw = do
...
beginPath ()
...
fill
```
This PR removes the `()` argument for `beginPath`, `clip`, `save`, `restore` and `stroke` so we can use them in the same way as `fill`.

Canvas: remove unnecessary () arguments

---

flake.lock
flake.nix
nix/source.nix

Now that native supports `flake.nix`, we can upstream to `miso`.

Adds a `flake.nix` for `miso`.

---

flake.nix
nix/haskell/packages/native/default.nix
nix/overlay.nix
nix/patches/jsbi.patch

This upstreams the patched GHCJS from [miso-lynx](https://github.com/dmjio/miso-lynx) that targets mobile JS runtimes into `miso`, exposed via its flake.

Upstream the native GHCJS into `miso`.

---

flake.lock
flake.nix

Credit to @amesgen, previously overlays were being exported but not used internally by the flake.
Updates `flake.lock` as well

Adjust overlays in `flake.nix`

---

miso.cabal

Specify a lower bound for `servant`. This avoids the resolver selecting the lowest version in some cases.

Specify `servant` lower bound

---

flake.nix
shell.nix

Adjust GHCJS 9.12.2 shell environment

---

examples/components/Main.hs
flake.nix
src/Miso.hs
src/Miso/Canvas.hs
src/Miso/Event.hs
src/Miso/FFI.hs
src/Miso/FFI/Internal.hs
src/Miso/Internal.hs
src/Miso/Types.hs

This PR adds a `Mailbox` to each `Component`. This means any `Component` can send any `Value` to any other `Component` (including itself). `ComponentId` can be obtained via on `onMountedWith` callback, or published to a `Topic` for distribution via the Pub / Sub mechanism (this can be done using the `onMounted` hook as well).

📬 Adds `Component` `mailbox`

---

src/Miso/Concurrent.hs
src/Miso/Event.hs
src/Miso/Internal.hs

Uses `cloneTChan` over `dupChan` for `Component` `Mailbox`. This ensures reads on `Component` `Mailbox` always refer to the contents of the original cloned `Mailbox`. Avoids missing messages potentially in a single reader scenario. For subscribers of `Topic` we should use `dupTChan` instead. `mail` should ensure reliable delivery, whereas `subscribe` is a notification stream.

Add `cloneMailbox`

---

src/Miso.hs
src/Miso/FFI/Internal.hs
src/Miso/Internal.hs
src/Miso/Types.hs

This is meant for development purposes primarily (similar to `renderStyles`). This allows dynamic appending of `<script>` to `<head>` on `Component` mount.
```haskell
main :: IO ()
main = run $ startComponent vcomp
{ styles =
[ Href "https://cdn.jsdelivr.net/npm/basecoat-css@0.2.8/dist/basecoat.cdn.min.css"
]
, scripts =
[ Src "https://cdn.tailwindcss.com"
, Script "(function () { alert ('hey'); })()"
]
}
```

Add `scripts :: [JS]`

---

.github/workflows/main.yml
default.nix
flake.nix
haskell-miso.org/nix/nginx.nix
nix/legacy/overlay.nix
nix/source.nix

Now that a `flake.nix` workflow has been incorporated per @juliendehos work, we can use that to host `more-examples` on github, instead of miso's nginx. This means `2048`, `flatris`, etc. are no longer being hosted by us

Use github links to host examples

---

haskell-miso.org/shared/Common.hs
src/Miso/Style/Color.hs

Allows users to specify `Color` as an `Int`
```haskell
λ> hex 0xAABBCC
Hex "aabbcc"
λ> renderColor (hex 0xAABBCC)
"#aabbcc"
```
This was inspired by [three.js](threejs.org)

Specify color as `Int` in hexadecimal.

---

src/Miso/Html/Property.hs
src/Miso/Mathml/Property.hs
src/Miso/Svg/Property.hs

Adds some missing properties required by [basecoat](https://basecoatui.com/), shuffles some others around. Adds `aria` helper.

Add additional properties

---

examples/components/Main.hs
src/Miso.hs
src/Miso/Effect.hs
src/Miso/Render.hs
src/Miso/Runtime.hs
src/Miso/Types.hs

Introduces `mount_`, renamed `component_`.
For usage,
```haskell
view m =
p_ [ key_ "my-component" ] +> 
component True noop $ \cond -> 
if cond then "true" else "false"
```
This solves the rogue `<div>` issue as seen in https://github.com/dmjio/miso/pull/1043, by allowing users to specify any tag type, while preserving the ability to specify a `key_`.

`component_` -> `mount_`. Allow mounting on any tag.

---

src/Miso/Types.hs

This is a bugfix. Inference led us astray here.

`mount` should parameterize HOF on `a`

---

src/Miso.hs
src/Miso/Runtime.hs

These functions are no longer necessary because we put `ComponentId` in the `Reader` for `Effect` and the new `parent` function in #1047 will subsume `getParentComponentId` (and further it uses the `FFI.Internal` variant).

Drop get* variant functions, prefer `parent`, use `ask`.

---

src/Miso/FFI.hs
src/Miso/FFI/Internal.hs

```haskell
test (Action domRef) = io_ $ do
domRef & click ()
```
This is useful when working with `FileReader` input.

Adds `click`

---

.github/workflows/main.yml

Now that we're hosting examples via GH pages we don't need this check. Can also drop GC too.

Drop example hosting checks in CI

---

src/Miso.hs
src/Miso/FFI.hs
src/Miso/FFI/Internal.hs
src/Miso/Media.hs

📷 Add `navigator.mediaDevices.getUserMedia` API

---

src/Miso/Types.hs

Right now users are forced to explicitly import `Miso.String`, this is necessary since it exposes an identical API to `Text`. But, the type `MisoString` can be exposed standalone, along with a subset of combinators that do not conflict with global
scope (e.g. `ms`,`toMisoString`, etc.).
This avoids additional imports on the user's behalf

Expose `MisoString`, `ms`, etc.

---

src/Miso.hs
src/Miso/Runtime.hs

Add `broadcast` primitive

---

src/Miso/Style.hs

Useful for avoiding `MisoString` concatenation.

Add `matrix` smart constructor

---

src/Miso/Subscription/Keyboard.hs

Use more efficient structure for `keyboardSub`

`Set Int` -> `IntSet`

---

miso.cabal
src/Miso/Run.hs

This means that usage of `CSS.url "mario.png"` w/ `Miso.Style` will "just work" when developing from GHCi. Assuming `'mario.png'` is in the same directory where GHCi is running.

Add `wai-middleware-static` to `Miso.Run` debug `Middleware`.

---

src/Miso/Lens/TH.hs

Otherwise `makeLenses` can complain `lens` isn't in scope (w/o importing `Miso.Lens`).

Re-export `lens` and `Lens` from `Miso.Lens.TH`.

---

src/Miso/FFI/Internal.hs
src/Miso/Subscription/History.hs
src/Miso/Subscription/Keyboard.hs
src/Miso/Subscription/SSE.hs
src/Miso/Subscription/WebSocket.hs
src/Miso/Subscription/Window.hs

This introduces the `bracket` pattern to `Sub`, specifically on `window`, this allows resource finalization and works well with top-level, long running `Sub`, or dynamically-generated `Sub` (`startSub`, `stopSub`).
To accomplish this, we are now returning `Function` from `addEventListener` too.

Add resource finalization on Window `Sub`.

---

miso.cabal
src/Miso/Canvas.hs
src/Miso/Subscription/Keyboard.hs
src/Miso/Subscription/SSE.hs
src/Miso/Subscription/Util.hs
src/Miso/Subscription/Window.hs
src/Miso/Types.hs

This factors out the resource finalization of `createSub` into a `Utils` module so other `Sub` can benefit from it.

Add `Miso.Subscription.Util.createSub`

---

src/Miso.hs
src/Miso/Runtime.hs

Runtime primitive for message passing any `ToJSON msg => msg` to a parent `Component`.

Add `mailParent`.

---

src/Miso/Lens.hs

This will modify a `Maybe` field in a record using a `Lens`, if the value is `Just`.
This is equivalent to
```haskell
(%?=) _lens f = _lens %= \case
Nothing -> Nothing
Just x -> Just (f x)
```
It's sort of like a hybrid between `?=` and `%=`

Adds the `(%?=)` combinator.

---

src/Miso/Svg/Element.hs

Update some SVG element combinators that don't require children.

`circle_`, `path_` require no chidren.

---

src/Miso/Event/Types.hs
src/Miso/Html/Event.hs

This is for the https://drag-and-drop.haskell-miso.org example.

Add `drag-*` variants that inlcude `Options`.

---

miso.cabal
src/Miso/Html/Element.hs
src/Miso/Html/Render.hs
src/Miso/Runtime.hs
src/Miso/String.hs
src/Miso/Types.hs

Now that `miso-from-html` can parse HTML into miso view syntax, we can recommend that over handling the "raw" text node case.
This also allows us to drop another inefficient dependency.

Drop `tagsoup`.

---

src/Miso/Effect.hs
src/Miso/Runtime.hs

This is necessary for native development API calls.

Add `componentParentId`, `rootComponentId`.

---

src/Miso/FFI/Internal.hs
src/Miso/Fetch.hs

Drops stringly-typed identifiers.

Use strong types for `fetch` `Content-Type`

---

src/Miso/Html/Render.hs

Properly escape characters when serializing to a text node.

Add `HTML` encoding on text nodes.
